"use strict";this.default_main=this.default_main||{};(function(_){var window=this;
try{
var aa,ba,ca,da;for(_.h,aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},ba="undefined"!=typeof window&&window===this?this:"undefined"!=typeof window.global?window.global:this,ca=["String","prototype","repeat"],da=0;da<ca.length-1;da++){var ea=ca[da];ea in ba||(ba[ea]={});ba=ba[ea]}
var fa=ca[ca.length-1],ga=ba[fa],ha=ga?ga:function(a){var b;if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");b=this+"";if(0>a||1342177279<a)throw new window.RangeError("Invalid count value");a|=0;for(var c="";a;)if(a&1&&(c+=b),a>>>=1)b+=b;return c};ha!=ga&&null!=ha&&aa(ba,fa,{configurable:!0,writable:!0,value:ha});_.ia=_.ia||{};_.l=this;_.ja="closure_uid_"+(1E9*Math.random()>>>0);_.m=Date.now||function(){return+new Date};

}catch(e){_._DumpException(e)}
try{
var ka,la,ma;_.n=function(a){return void 0!==a};ka=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};la=function(a,b,c){return a.call.apply(a.bind,arguments)};
ma=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.q=function(a,b){function c(){}c.prototype=b.prototype;a.B=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.nc=function(a,c,f){for(var g=Array(arguments.length-2),k=2;k<arguments.length;k++)g[k-2]=arguments[k];return b.prototype[c].apply(a,g)}};
_.na=function(a,b){var c=a.split("."),d=_.l;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&_.n(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}};_.oa=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.r=function(a,b,c){_.r=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?la:ka;return _.r.apply(null,arguments)};
_.pa=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.t=function(a){return"function"==ma(a)};_.qa=function(a){return"number"==typeof a};_.u=function(a){return"string"==typeof a};_.ra=function(a){var b=ma(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.sa=function(a){return"array"==ma(a)};_.ta=function(){};_.ua=function(a,b){for(var c=a.split("."),d=b||_.l,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d}; _.va=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.va);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};_.q(_.va,Error);_.va.prototype.name="CustomError";
var wa=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},xa=function(a,b){return a<b?-1:a>b?1:0};_.ya=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.u(a))return _.u(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};_.za=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.u(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.Aa=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=_.u(a)?a.split(""):a,k=0;k<d;k++)if(k in g){var p=g[k];b.call(c,p,k,a)&&(e[f++]=p)}return e};_.Ba=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=_.u(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};
_.Ca=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.u(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.Da=function(a,b){var c=(0,_.ya)(a,b),d;(d=0<=c)&&Array.prototype.splice.call(a,c,1);return d};
a:{var Fa=_.l.navigator;if(Fa){var Ga=Fa.userAgent;if(Ga){_.Ea=Ga;break a}}_.Ea=""}_.v=function(a){return-1!=_.Ea.indexOf(a)};var Ia;_.Ha=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};Ia=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};_.Ja=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};var Ka=function(){return(_.v("Chrome")||_.v("CriOS"))&&!_.v("Edge")};_.La=function(){return _.v("iPhone")&&!_.v("iPod")&&!_.v("iPad")};var Ma=function(a){Ma[" "](a);return a},Pa;Ma[" "]=_.ta;_.Na=function(a,b){try{return Ma(a[b]),!0}catch(c){}return!1};Pa=function(a,b){var c=Oa;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var Wa,Ya,Za,Oa,eb,fb;_.Qa=_.v("Opera");_.w=_.v("Trident")||_.v("MSIE");_.Ta=_.v("Edge");_.Ua=_.v("Gecko")&&!(-1!=_.Ea.toLowerCase().indexOf("webkit")&&!_.v("Edge"))&&!(_.v("Trident")||_.v("MSIE"))&&!_.v("Edge");_.Va=-1!=_.Ea.toLowerCase().indexOf("webkit")&&!_.v("Edge");Wa=_.l.navigator||null;_.Xa=Wa&&Wa.platform||"";Ya=function(){var a=_.l.document;return a?a.documentMode:void 0};
a:{var $a="",ab=function(){var a=_.Ea;if(_.Ua)return/rv\:([^\);]+)(\)|;)/.exec(a);if(_.Ta)return/Edge\/([\d\.]+)/.exec(a);if(_.w)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.Va)return/WebKit\/(\S+)/.exec(a);if(_.Qa)return/(?:Version)[ \/]?(\S+)/.exec(a)}();ab&&($a=ab?ab[1]:"");if(_.w){var bb=Ya();if(null!=bb&&bb>(0,window.parseFloat)($a)){Za=String(bb);break a}}Za=$a}_.cb=Za;Oa={};
_.db=function(a){return Pa(a,function(){for(var b=0,c=wa(String(_.cb)).split("."),d=wa(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",k=d[f]||"";do{g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];if(0==g[0].length&&0==k[0].length)break;b=xa(0==g[1].length?0:(0,window.parseInt)(g[1],10),0==k[1].length?0:(0,window.parseInt)(k[1],10))||xa(0==g[2].length,0==k[2].length)||xa(g[2],k[2]);g=g[3];k=k[3]}while(0==b)}return 0<=b})}; eb=_.l.document;fb=eb&&_.w?Ya()||("CSS1Compat"==eb.compatMode?(0,window.parseInt)(_.cb,10):5):void 0;
_.hb=_.v("Firefox");_.ib=_.La()||_.v("iPod");_.jb=_.v("iPad");_.kb=_.v("Android")&&!(Ka()||_.v("Firefox")||_.v("Opera")||_.v("Silk"));_.lb=Ka();_.mb=_.v("Safari")&&!(Ka()||_.v("Coast")||_.v("Opera")||_.v("Edge")||_.v("Silk")||_.v("Android"))&&!(_.La()||_.v("iPad")||_.v("iPod"));
_.nb=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;var ob,rb,sb;_.x=function(){};ob="function"==typeof window.Uint8Array;_.y=function(a,b,c,d){a.a=null;b||(b=c?[c]:[]);a.D=c?String(c):void 0;a.f=0===c?-1:0;a.b=b;a:{if(a.b.length&&(b=a.b.length-1,(c=a.b[b])&&"object"==typeof c&&!_.sa(c)&&!(ob&&c instanceof window.Uint8Array))){a.u=b-a.f;a.c=c;break a}a.u=Number.MAX_VALUE}a.C={};if(d)for(b=0;b<d.length;b++)c=d[b],c<a.u?(c+=a.f,a.b[c]=a.b[c]||_.pb):a.c[c]=a.c[c]||_.pb};_.pb=[];
_.z=function(a,b){if(b<a.u){var c=b+a.f,d=a.b[c];return d===_.pb?a.b[c]=[]:d}d=a.c[b];return d===_.pb?a.c[b]=[]:d};rb=function(a){if(a.a)for(var b in a.a){var c=a.a[b];if(_.sa(c))for(var d=0;d<c.length;d++)c[d]&&_.qb(c[d]);else c&&_.qb(c)}};_.qb=function(a){rb(a);return a.b};_.x.prototype.toString=function(){rb(this);return this.b.toString()};_.A=function(a,b){sb[a]=b;b.messageId=a};sb={};
_.tb=function(a){return function(){return a}}(!0);_.ub="StopIteration"in _.l?_.l.StopIteration:{message:"StopIteration",stack:""};_.vb=function(){};_.vb.prototype.next=function(){throw _.ub;};_.vb.prototype.Y=function(){return this};_.C=function(a,b){this.b={};this.a=[];this.f=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("e");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof _.C?(c=a.M(),d=a.G()):(c=_.Ja(a),d=Ia(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};_.h=_.C.prototype;_.h.ba=function(){return this.c};_.h.G=function(){wb(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};_.h.M=function(){wb(this);return this.a.concat()};
_.h.clear=function(){this.b={};this.f=this.c=this.a.length=0};_.h.remove=function(a){return _.xb(this.b,a)?(delete this.b[a],this.c--,this.f++,this.a.length>2*this.c&&wb(this),!0):!1};var wb=function(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];_.xb(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],_.xb(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};_.C.prototype.get=function(a,b){return _.xb(this.b,a)?this.b[a]:b};
_.C.prototype.set=function(a,b){_.xb(this.b,a)||(this.c++,this.a.push(a),this.f++);this.b[a]=b};_.C.prototype.forEach=function(a,b){for(var c=this.M(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};_.C.prototype.Y=function(a){wb(this);var b=0,c=this.f,d=this,e=new _.vb;e.next=function(){if(c!=d.f)throw Error("f");if(b>=d.a.length)throw _.ub;var e=d.a[b++];return a?e:d.b[e]};return e};_.xb=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
_.yb=function(a){if(a.G&&"function"==typeof a.G)return a.G();if(_.u(a))return a.split("");if(_.ra(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Ia(a)};_.D=function(){this.K=this.K;this.u=this.u};_.D.prototype.K=!1;_.D.prototype.N=function(){this.K||(this.K=!0,this.v())};_.F=function(a,b){_.zb(a,_.oa(_.E,b))};_.zb=function(a,b){a.K?_.n(void 0)?b.call(void 0):b():(a.u||(a.u=[]),a.u.push(_.n(void 0)?(0,_.r)(b,void 0):b))};_.D.prototype.v=function(){if(this.u)for(;this.u.length;)this.u.shift()()};_.E=function(a){a&&"function"==typeof a.N&&a.N()};
_.Ab=!_.w||9<=Number(fb);!_.Ua&&!_.w||_.w&&9<=Number(fb)||_.Ua&&_.db("1.9.1");_.w&&_.db("9");var Bb=!_.w||9<=Number(fb),Cb=_.w&&!_.db("9");!_.Va||_.db("528");_.Ua&&_.db("1.9b")||_.w&&_.db("8")||_.Qa&&_.db("9.5")||_.Va&&_.db("528");_.Ua&&!_.db("8")||_.w&&_.db("9");_.Db=function(a,b){this.type=a;this.a=this.b=b;this.eb=!0};_.Db.prototype.c=function(){this.eb=!1};var Eb=function(a,b){_.Db.call(this,a?a.type:"");this.f=this.state=this.a=this.b=null;a&&this.T(a,b)};_.q(Eb,_.Db);Eb.prototype.T=function(a,b){this.type=a.type;this.b=a.target||a.srcElement;this.a=b;var c=a.relatedTarget;c&&_.Ua&&_.Na(c,"nodeName");this.state=a.state;this.f=a;a.defaultPrevented&&this.c()};Eb.prototype.c=function(){Eb.B.c.call(this);var a=this.f;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Cb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var Fb,Hb;Fb="closure_listenable_"+(1E6*Math.random()|0);_.Gb=function(a){return!(!a||!a[Fb])};Hb=0;var Ib=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.ma=!!d;this.oa=e;this.key=++Hb;this.removed=this.la=!1},Jb=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.oa=null};var Kb;Kb=function(a){this.src=a;this.a={};this.b=0};_.Mb=function(a,b,c,d,e,f){var g=b.toString();b=a.a[g];b||(b=a.a[g]=[],a.b++);var k=Lb(b,c,e,f);-1<k?(a=b[k],d||(a.la=!1)):(a=new Ib(c,a.src,g,!!e,f),a.la=d,b.push(a));return a};Kb.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Lb(e,b,c,d);return-1<b?(Jb(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var Nb=function(a,b){var c=b.type;c in a.a&&_.Da(a.a[c],b)&&(Jb(b),0==a.a[c].length&&(delete a.a[c],a.b--))};Kb.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,Jb(d[e]);delete this.a[c];this.b--}return b};var Ob=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=Lb(a,c,d,e));return-1<b?a[b]:null},Lb=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.ma==!!c&&f.oa==d)return e}return-1};
var Pb,Qb,Rb,Wb,Zb,$b,Xb,bc,ac,Yb,Vb,cc;Pb="closure_lm_"+(1E6*Math.random()|0);Qb={};Rb=0;_.Sb=function(a,b,c,d,e){if(_.sa(b)){for(var f=0;f<b.length;f++)_.Sb(a,b[f],c,d,e);return null}c=_.Tb(c);return _.Gb(a)?a.listen(b,c,d,e):_.Ub(a,b,c,!1,d,e)};
_.Ub=function(a,b,c,d,e,f){if(!b)throw Error("i");var g=!!e,k=Vb(a);k||(a[Pb]=k=new Kb(a));c=_.Mb(k,b,c,d,e,f);if(c.proxy)return c;d=Wb();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,g);else if(a.attachEvent)a.attachEvent(Xb(b.toString()),d);else throw Error("j");Rb++;return c};Wb=function(){var a=Yb,b=Bb?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b};
Zb=function(a,b,c,d,e){if(_.sa(b))for(var f=0;f<b.length;f++)Zb(a,b[f],c,d,e);else c=_.Tb(c),_.Gb(a)?a.Ca(b,c,d,e):a&&(a=Vb(a))&&(b=Ob(a,b,c,!!d,e))&&$b(b)};$b=function(a){if(_.qa(a)||!a||a.removed)return;var b=a.src;if(_.Gb(b)){Nb(b.c,a);return}var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.ma):b.detachEvent&&b.detachEvent(Xb(c),d);Rb--;(c=Vb(b))?(Nb(c,a),0==c.b&&(c.src=null,b[Pb]=null)):Jb(a)};Xb=function(a){return a in Qb?Qb[a]:Qb[a]="on"+a};
bc=function(a,b,c,d){var e=!0;if(a=Vb(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.ma==c&&!f.removed&&(f=ac(f,d),e=e&&!1!==f)}return e};ac=function(a,b){var c=a.listener,d=a.oa||a.src;a.la&&$b(a);return c.call(d,b)};
Yb=function(a,b){if(a.removed)return!0;if(!Bb){var c=b||_.ua("window.event"),d=new Eb(c,this),e=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var f=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(p){f=!0}if(f||void 0==c.returnValue)c.returnValue=!0}c=[];for(f=d.a;f;f=f.parentNode)c.push(f);for(var f=a.type,g=c.length-1;0<=g;g--){d.a=c[g];var k=bc(c[g],f,!0,d),e=e&&k}for(g=0;g<c.length;g++)d.a=c[g],k=bc(c[g],f,!1,d),e=e&&k}return e}return ac(a,new Eb(b,this))}; Vb=function(a){a=a[Pb];return a instanceof Kb?a:null};cc="__closure_events_fn_"+(1E9*Math.random()>>>0);_.Tb=function(a){if(_.t(a))return a;a[cc]||(a[cc]=function(b){return a.handleEvent(b)});return a[cc]};
_.dc=function(a){_.y(this,a,"h_cc",null)};_.q(_.dc,_.x);_.A("h_cc",_.dc);_.dc.prototype.S=function(){return _.z(this,19)};_.G=function(a){this.a=a};_.G.prototype.toString=function(){return this.a};_.H=function(a){_.D.call(this);this.I=a;this.f={}};_.q(_.H,_.D);var ec=[];_.H.prototype.listen=function(a,b,c,d){return _.fc(this,a,b,c,d)};_.fc=function(a,b,c,d,e,f){_.sa(c)||(c&&(ec[0]=c.toString()),c=ec);for(var g=0;g<c.length;g++){var k=_.Sb(b,c[g],d||a.handleEvent,e||!1,f||a.I||a);if(!k)break;a.f[k.key]=k}return a};
_.H.prototype.Ca=function(a,b,c,d,e){if(_.sa(b))for(var f=0;f<b.length;f++)this.Ca(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.I||this,c=_.Tb(c),d=!!d,b=_.Gb(a)?Ob(a.c,String(b),c,d,e):a?(a=Vb(a))?Ob(a,b,c,d,e):null:null,b&&($b(b),delete this.f[b.key]);return this};_.H.prototype.removeAll=function(){_.Ha(this.f,function(a,b){this.f.hasOwnProperty(b)&&$b(a)},this);this.f={}};_.H.prototype.v=function(){_.H.B.v.call(this);this.removeAll()}; _.H.prototype.handleEvent=function(){throw Error("m");};
var gc=function(a,b,c){this.f=c;this.c=a;this.u=b;this.b=0;this.a=null};gc.prototype.get=function(){var a;0<this.b?(this.b--,a=this.a,this.a=a.next,a.next=null):a=this.c();return a};var hc=function(a,b){a.u(b);a.b<a.f&&(a.b++,b.next=a.a,a.a=b)};var ic,jc,kc;ic=function(a){_.l.setTimeout(function(){throw a;},0)};_.lc=function(a,b){var c=a;b&&(c=(0,_.r)(a,b));!_.t(_.l.setImmediate)||_.l.Window&&_.l.Window.prototype&&!_.v("Edge")&&_.l.Window.prototype.setImmediate==_.l.setImmediate?(jc||(jc=kc()),jc(c)):_.l.setImmediate(c)};
kc=function(){var a=_.l.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!_.v("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,_.r)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!_.v("Trident")&&!_.v("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.n(c.next)){c=c.next;var a=c.Va;c.Va=null;a()}};return function(a){d.next={Va:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b= window.document.createElement("SCRIPT");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){_.l.setTimeout(a,0)}};
var mc=function(){this.b=this.a=null},oc=new gc(function(){return new nc},function(a){a.reset()},100);mc.prototype.remove=function(){var a=null;this.a&&(a=this.a,this.a=this.a.next,this.a||(this.b=null),a.next=null);return a};var nc=function(){this.next=this.b=this.a=null};nc.prototype.set=function(a,b){this.a=a;this.b=b;this.next=null};nc.prototype.reset=function(){this.next=this.b=this.a=null};
var tc=function(a,b){pc||qc();rc||(pc(),rc=!0);var c=sc,d=oc.get();d.set(a,b);c.b?c.b.next=d:c.a=d;c.b=d},pc,qc=function(){if(_.l.Promise&&_.l.Promise.resolve){var a=_.l.Promise.resolve(void 0);pc=function(){a.then(uc)}}else pc=function(){_.lc(uc)}},rc=!1,sc=new mc,uc=function(){for(var a;a=sc.remove();){try{a.a.call(a.b)}catch(b){ic(b)}hc(oc,a)}rc=!1};
_.I=function(){_.D.call(this);this.c=new Kb(this);this.O=this;this.D=null};_.q(_.I,_.D);_.I.prototype[Fb]=!0;_.h=_.I.prototype;_.h.removeEventListener=function(a,b,c,d){Zb(this,a,b,c,d)};_.h.v=function(){_.I.B.v.call(this);this.c&&this.c.removeAll(void 0);this.D=null};_.h.listen=function(a,b,c,d){return _.Mb(this.c,String(a),b,!1,c,d)};_.h.Ca=function(a,b,c,d){return this.c.remove(String(a),b,c,d)}; _.h.X=function(a,b,c){a=this.c.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.ma==b){var g=f.listener,k=f.oa||f.src;f.la&&Nb(this.c,f);d=!1!==g.call(k,c)&&d}}return d&&0!=c.eb};
var vc=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},wc=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var yc=function(a,b){this.a=0;this.h=void 0;this.c=this.b=this.f=null;this.u=this.g=!1;if(a!=_.ta)try{var c=this;a.call(b,function(a){xc(c,2,a)},function(a){xc(c,3,a)})}catch(d){xc(this,3,d)}},zc=function(){this.next=this.c=this.b=this.f=this.a=null;this.u=!1},Ac,Bc;zc.prototype.reset=function(){this.c=this.b=this.f=this.a=null;this.u=!1};Ac=new gc(function(){return new zc},function(a){a.reset()},100);Bc=function(a,b,c){var d=Ac.get();d.f=a;d.b=b;d.c=c;return d};
_.Dc=function(){var a,b=new yc(function(b){a=b});return new Cc(b,a)};yc.prototype.then=function(a,b,c){return Ec(this,_.t(a)?a:null,_.t(b)?b:null,c)};vc(yc);
var Gc=function(a,b){a.b||2!=a.a&&3!=a.a||Fc(a);a.c?a.c.next=b:a.b=b;a.c=b},Ec=function(a,b,c,d){var e=Bc(null,null,null);e.a=new yc(function(a,g){e.f=b?function(c){try{var e=b.call(d,c);a(e)}catch(B){g(B)}}:a;e.b=c?function(b){try{var e=c.call(d,b);!_.n(e)&&"undefined"!=typeof Hc&&b instanceof Hc?g(b):a(e)}catch(B){g(B)}}:g});e.a.f=a;Gc(a,e);return e.a};yc.prototype.l=function(a){this.a=0;xc(this,2,a)};yc.prototype.w=function(a){this.a=0;xc(this,3,a)};
var xc=function(a,b,c){if(0==a.a){a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.a=1;var d;a:{var e=c,f=a.l,g=a.w;if(e instanceof yc)Gc(e,Bc(f||_.ta,g||null,a)),d=!0;else if(wc(e))e.then(f,g,a),d=!0;else{if(_.pa(e))try{var k=e.then;if(_.t(k)){Ic(e,k,f,g,a);d=!0;break a}}catch(p){g.call(a,p);d=!0;break a}d=!1}}d||(a.h=c,a.a=b,a.f=null,Fc(a),3!=b||"undefined"!=typeof Hc&&c instanceof Hc||Jc(a,c))}},Ic=function(a,b,c,d,e){var f=!1,g=function(a){f||(f=!0,c.call(e,a))},k=function(a){f||
(f=!0,d.call(e,a))};try{b.call(a,g,k)}catch(p){k(p)}},Fc=function(a){a.g||(a.g=!0,tc(a.j,a))},Kc=function(a){var b=null;a.b&&(b=a.b,a.b=b.next,b.next=null);a.b||(a.c=null);return b};yc.prototype.j=function(){for(var a;a=Kc(this);){var b=this.a,c=this.h;if(3==b&&a.b&&!a.u){var d;for(d=this;d&&d.u;d=d.f)d.u=!1}if(a.a)a.a.f=null,Lc(a,b,c);else try{a.u?a.f.call(a.c):Lc(a,b,c)}catch(e){Mc.call(null,e)}hc(Ac,a)}this.g=!1}; var Lc=function(a,b,c){2==b?a.f.call(a.c,c):a.b&&a.b.call(a.c,c)},Jc=function(a,b){a.u=!0;tc(function(){a.u&&Mc.call(null,b)})},Mc=ic,Hc=function(a){_.va.call(this,a)};_.q(Hc,_.va);Hc.prototype.name="cancel";var Cc=function(a,b){this.b=a;this.a=b};
_.Nc=function(a,b){for(var c=[],d=0;d<arguments.length;d++)c.push(arguments[d]||"");return c.join("_;_")};_.Oc=function(){return 0<=window.navigator.userAgent.indexOf("CrOS")};_.J=function(a,b){this.g=a||"e";this.u=null!=a&&"p"==a?"e":"p";this.a=this.f=null;this.j=b||"u";this.c=this.h=null;this.b=[]};_.J.prototype.message=function(){var a={};a.i=this.c;a.m=this.b;a.r=this.j;a.o=this.h;a.s=this.a;a.st=this.u;a.d=this.f;a.dt=this.g;return a};_.J.prototype.message=_.J.prototype.message;
_.Pc=function(a,b){for(var c in b)switch(c){case "r":a.j=b[c];break;case "i":a.c=b[c];break;case "m":a.b=b[c];break;case "o":a.h=b[c];break;case "s":a.a=b[c];break;case "d":a.f=b[c];break;case "st":a.u=b[c];break;case "dt":a.g=b[c]}return a};_.Qc=function(a,b,c){null!=b&&(a.a=b,null!=c&&(a.u=c))};_.Rc=function(a,b){null!=b&&(a.c=b)};_.Sc=function(a,b){"object"==typeof b?a.b=b:a.b=[b]};
_.Tc=function(a,b,c,d,e){_.D.call(this);this.b=a;this.ja=b;this.a=typeof b;this.za=c?c:!1;this.W=!0;this.ya=d?d:!1;this.ua=e?e:!1};_.q(_.Tc,_.D);_.h=_.Tc.prototype;_.h.v=function(){_.Tc.B.v.call(this);this.b="";this.ja=null;this.a=""};_.h.id=function(){return this.b};_.h.type=function(){return this.a};_.h.F=function(){return this.ja};_.h.setEnabled=function(a){this.W=a};
_.Vc=function(a){_.D.call(this);this.a=new _.C;this.b=["https://hangouts.google.com","","https://autopush.hangouts.sandbox.google.com?jsmode=du"];a&&_.Uc(this,a)};_.q(_.Vc,_.D);_.Wc=!_.Oc();_.Vc.prototype.v=function(){_.Vc.B.v.call(this);for(var a=this.a.M(),b=0;b<a.length;++b)_.E(this.a.get(a[b]));delete this.a};_.Vc.prototype.getItem=function(a){return _.xb(this.a.b,a)?this.a.get(a):null};_.Vc.prototype.setItem=function(a){this.a.set(a.id(),a)}; _.Uc=function(a,b){for(var c in b){var d=b[c],e;_.xb(a.a.b,c)?(e=a.a.get(c),e.ja=d.value,d.changed&&(e.ua=d.changed)):(e=new _.Tc(c,d.value,d.multiple,d.inverse,d.changed),e.setEnabled(!d.disabled));a.a.set(c,e)}};
_.Yc=function(){this.b=new _.C;this.a=null;this.c=!1;window.chrome.storage||(this.a=new Xc,this.c=!0);this.T()};_.Yc.ca=function(){return _.Yc.a?_.Yc.a:_.Yc.a=new _.Yc};_.h=_.Yc.prototype;_.h.T=function(a){var b=a||_.ta;this.c?b():window.chrome.storage.local.get((0,_.r)(function(a){if(!this.c){for(var d in a)this.b.set(d,a[d]);this.c=!0}b()},this))};_.h.get=function(a){return window.chrome.storage?this.b.get(a,null):this.a.get(a)};
_.h.has=function(a){return window.chrome.storage?_.xb(this.b.b,a):this.a.has(a)};_.h.set=function(a,b){var c=_.Dc();if(window.chrome.storage){this.b.set(a,b);var d={};d[a]=b;window.chrome.storage.local.set(d,function(){c.a(void 0)})}else this.a.set(a,b),c.a(void 0);return c.b};_.h.remove=function(a){window.chrome.storage?(this.b.remove(a),window.chrome.storage.local.remove(a,function(){})):this.a.remove(a)};
_.h.clear=function(){window.chrome.storage?(this.b.clear(),window.chrome.storage.local.clear(function(){})):this.a.clear()};var Xc=function(){this.a=window.localStorage};_.h=Xc.prototype;_.h.clear=function(){this.a.clear()};_.h.get=function(a){a=this.a.getItem(a);if(a){var b=JSON.parse(a);a=b.data;if("jspb"==b.type){b=sb[a[0]];if(!b)throw Error("c`"+a[0]);a=new b(a)}}else a=null;return a};_.h.has=function(a){return null!=this.get(a)}; _.h.set=function(a,b){var c=null;b instanceof _.x&&(b=_.qb(b),c="jspb");var d={};d.data=b;d.timestamp=(0,_.m)();c&&(d.type=c);c=JSON.stringify(d);try{this.a.setItem(a,c)}catch(e){}};_.h.remove=function(a){try{this.a.removeItem(a)}catch(b){}};
/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
var Zc=function(a,b){this.f=[];this.D=b||null;this.a=this.b=!1;this.c=void 0;this.l=this.w=this.g=!1;this.u=0;this.h=null;this.A=0};Zc.prototype.j=function(a,b){this.g=!1;this.b=!0;this.c=b;this.a=!a;$c(this)};Zc.prototype.C=function(a){if(this.b){if(!this.l)throw new ad;this.l=!1}this.b=!0;this.c=a;this.a=!1;$c(this)};var bd=function(a,b,c){a.f.push([b,c,void 0]);a.b&&$c(a)};
Zc.prototype.then=function(a,b,c){var d,e,f=new yc(function(a,b){d=a;e=b});bd(this,d,function(a){e(a)});return f.then(a,b,c)};vc(Zc);
var cd=function(a){return(0,_.Ca)(a.f,function(a){return _.t(a[1])})},$c=function(a){if(a.u&&a.b&&cd(a)){var b=a.u,c=dd[b];c&&(_.l.clearTimeout(c.a),delete dd[b]);a.u=0}a.h&&(a.h.A--,delete a.h);for(var b=a.c,d=c=!1;a.f.length&&!a.g;){var e=a.f.shift(),f=e[0],g=e[1],e=e[2];if(f=a.a?g:f)try{var k=f.call(e||a.D,b);_.n(k)&&(a.a=a.a&&(k==b||k instanceof Error),a.c=b=k);if(wc(b)||"function"===typeof _.l.Promise&&b instanceof _.l.Promise)d=!0,a.g=!0}catch(p){b=p,a.a=!0,cd(a)||(c=!0)}}a.c=b;d&&(k=(0,_.r)(a.j,
a,!0),d=(0,_.r)(a.j,a,!1),b instanceof Zc?(bd(b,k,d),b.w=!0):b.then(k,d));c&&(b=new ed(b),dd[b.a]=b,a.u=b.a)},ad=function(){_.va.call(this)};_.q(ad,_.va);ad.prototype.message="Deferred has already fired";ad.prototype.name="AlreadyCalledError";var ed=function(a){this.a=_.l.setTimeout((0,_.r)(this.c,this),0);this.b=a};ed.prototype.c=function(){delete dd[this.a];throw this.b;};var dd={};

}catch(e){_._DumpException(e)}
try{
var hd;_.fd=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);else if(_.ra(a)||_.u(a))(0,_.za)(a,b,void 0);else{var c;if(a.M&&"function"==typeof a.M)c=a.M();else if(a.G&&"function"==typeof a.G)c=void 0;else if(_.ra(a)||_.u(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=_.Ja(a);for(var d=_.yb(a),e=d.length,f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}};_.gd=function(a){a&&a.parentNode&&a.parentNode.removeChild(a)}; hd=function(a,b){for(var c=_.u(a)?a.split(""):a,d=a.length-1;0<=d;--d)d in c&&b.call(void 0,c[d],d,a)};
var id=function(a,b){this.c=a;this.b=b;this.constructor.Ua||(this.constructor.Ua={});this.constructor.Ua[this.toString()]=this};id.prototype.toString=function(){this.a||(this.a=this.c.a+":"+this.b);return this.a};var jd=function(a,b){id.call(this,a,b)};_.q(jd,id);var kd=function(a){this.a=a};new kd("lib");_.md=function(a){_.D.call(this);this.b={};this.l={};this.w={};this.f={};this.A={};this.D={};this.C=a?a.g():new _.I;this.J=!a;this.h=null;a?(this.h=a,this.w=a.w,this.f=a.f,this.l=a.l,this.A=a.A):(0,_.m)();a=ld(this);this!=a&&(a.j?a.j.push(this):a.j=[this])};_.q(_.md,_.D);var ld=function(a){for(;a.h;)a=a.h;return a};_.md.prototype.get=function(a){var b=this.c(a);if(null==b)throw new nd(a);return b};
_.md.prototype.c=function(a){for(var b=this;b;b=b.h){if(b.K)throw Error("o");if(b.b[a])return b.b[a][0];if(b.D[a])break}if(b=this.w[a]){b=b(this);if(null==b)throw Error("p`"+a);this.a(a,b);return b}return null};_.md.prototype.a=function(a,b,c){if(this.K)c||_.E(b);else{this.b[a]=[b,!c];b=od(this,this,a);for(c=0;c<b.length;c++)b[c].C(null);delete this.l[a]}};_.md.prototype.I=function(){var a=_.pd;if(!this.b[a])throw Error("q`"+a);var b=this.b[a];delete this.b[a];b[1]&&_.E(b[0])};
var od=function(a,b,c){var d=[],e=a.f[c];e&&(hd(e,function(a){var c;a:{for(c=a.qb;c;){if(c==b){c=!0;break a}c=c.h}c=!1}c&&(d.push(a.d),_.Da(e,a))}),0==e.length&&delete a.f[c]);return d},qd=function(a,b){a.f&&_.fd(a.f,function(a,d,e){hd(a,function(d){d.qb==b&&_.Da(a,d)});0==a.length&&delete e[d]})};
_.md.prototype.v=function(){if(ld(this)==this){var a=this.j;if(a)for(;a.length;)a[0].N()}else for(var a=ld(this).j,b=0;b<a.length;b++)if(a[b]==this){a.splice(b,1);break}for(var c in this.b)a=this.b[c],a[1]&&a[0].N&&a[0].N();this.b=null;this.J&&this.C.N();qd(this,this);this.f=null;_.E(this.H);this.D=this.H=null;_.md.B.v.call(this)};_.md.prototype.g=function(){return this.C};var nd=function(a){_.va.call(this);this.id=a;this.message='Service for "'+a+'" is not registered'};_.q(nd,_.va);var rd=new kd("fva"); new jd(rd,1);

}catch(e){_._DumpException(e)}
try{
var sd,td,ud,Ad,Bd,Cd,Gd,Hd,Id,Ld,Md,Nd,Od,Pd,Qd,Rd,Td,Ud,Vd;sd=function(a,b,c,d,e){if(_.sa(b)){for(var f=0;f<b.length;f++)sd(a,b[f],c,d,e);return null}c=_.Tb(c);return _.Gb(a)?_.Mb(a.c,String(b),c,!0,d,e):_.Ub(a,b,c,!0,d,e)};td="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");ud=function(a,b,c,d,e,f){if(_.sa(c))for(var g=0;g<c.length;g++)ud(a,b,c[g],d,e,f);else{b=sd(b,c,d||a.handleEvent,e,f||a.I||a);if(!b)return a;a.f[b.key]=b}return a};
_.L=function(a,b,c){b<a.u?a.b[b+a.f]=c:a.c[b]=c};_.vd=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<td.length;f++)c=td[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};_.wd=function(a,b,c){null!=b&&(a.f=b,null!=c&&(a.g=c))};
_.M=function(a,b){var c,d=a.D;if(d)for(c=[];d;d=d.D)c.push(d);var d=a.O,e=b,f=e.type||e;if(_.u(e))e=new _.Db(e,d);else if(e instanceof _.Db)e.b=e.b||d;else{var g=e,e=new _.Db(f,d);_.vd(e,g)}var g=!0,k;if(c)for(var p=c.length-1;0<=p;p--)k=e.a=c[p],g=k.X(f,!0,e)&&g;k=e.a=d;g=k.X(f,!0,e)&&g;g=k.X(f,!1,e)&&g;if(c)for(p=0;p<c.length;p++)k=e.a=c[p],g=k.X(f,!1,e)&&g};_.xd=function(a,b,c,d){return ud(a,b,c,d,void 0)};_.yd=function(a,b,c){a.a||(a.a={});var d=c?_.qb(c):c;a.a[b]=c;_.L(a,b,d)};
_.zd=function(a,b,c){a.a||(a.a={});if(!a.a[c]){var d=_.z(a,c);d&&(a.a[c]=new b(d))}return a.a[c]};Ad=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)};Bd=function(a,b){return a?b?(0,window.decodeURI)(a.replace(/%25/g,"%2525")):(0,window.decodeURIComponent)(a):""};
Cd=function(a,b){if(a)for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].indexOf("="),f,g=null;0<=e?(f=c[d].substring(0,e),g=c[d].substring(e+1)):f=c[d];b(f,g?(0,window.decodeURIComponent)(g.replace(/\+/g," ")):"")}};_.Dd=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;_.Ed=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
_.Fd=function(a){return Array.prototype.concat.apply(Array.prototype,arguments)};Gd=function(a,b,c){this.b=this.a=null;this.c=a||null;this.f=!!c};Hd=function(a){a.a||(a.a=new _.C,a.b=0,a.c&&Cd(a.c,function(b,c){var d=(0,window.decodeURIComponent)(b.replace(/\+/g," "));Hd(a);a.c=null;var d=Id(a,d),e=a.a.get(d);e||a.a.set(d,e=[]);e.push(c);a.b+=1}))};Gd.prototype.ba=function(){Hd(this);return this.b};
Gd.prototype.remove=function(a){Hd(this);a=Id(this,a);return _.xb(this.a.b,a)?(this.c=null,this.b-=this.a.get(a).length,this.a.remove(a)):!1};Gd.prototype.clear=function(){this.a=this.c=null;this.b=0};var Jd=function(a,b){Hd(a);b=Id(a,b);return _.xb(a.a.b,b)};Gd.prototype.M=function(){Hd(this);for(var a=this.a.G(),b=this.a.M(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
Gd.prototype.G=function(a){Hd(this);var b=[];if(_.u(a))Jd(this,a)&&(b=_.Fd(b,this.a.get(Id(this,a))));else{a=this.a.G();for(var c=0;c<a.length;c++)b=_.Fd(b,a[c])}return b};Gd.prototype.set=function(a,b){Hd(this);this.c=null;a=Id(this,a);Jd(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};Gd.prototype.get=function(a,b){var c=a?this.G(a):[];return 0<c.length?String(c[0]):b};_.Kd=function(a,b,c){a.remove(b);0<c.length&&(a.c=null,a.a.set(Id(a,b),_.Ed(c)),a.b+=c.length)};
Gd.prototype.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.M(),c=0;c<b.length;c++)for(var d=b[c],e=(0,window.encodeURIComponent)(String(d)),d=this.G(d),f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+(0,window.encodeURIComponent)(String(d[f])));a.push(g)}return this.c=a.join("&")};Id=function(a,b){var c=String(b);a.f&&(c=c.toLowerCase());return c};
Ld=function(a,b){b&&!a.f&&(Hd(a),a.c=null,a.a.forEach(function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),_.Kd(this,e,a))},a));a.f=b};Md=/#/g;Nd=/[\#\?@]/g;Od=/[\#\?]/g;Pd=/[\#\?:]/g;Qd=/[#\/\?@]/g;Rd=function(a,b,c){return _.u(a)?(a=(0,window.encodeURI)(a).replace(b,Ad),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null};
_.Sd=function(a,b){this.c=this.j=this.u="";this.f=null;this.g=this.a="";this.h=!1;var c;if("undefined"!=typeof _.Sd&&a instanceof _.Sd){this.h=_.n(b)?b:a.h;Td(this,a.u);this.j=a.j;this.c=a.c;Ud(this,a.f);this.a=a.a;c=a.b;var d=new Gd;d.c=c.c;c.a&&(d.a=new _.C(c.a),d.b=c.b);Vd(this,d);this.g=a.g}else a&&(c=String(a).match(_.Dd))?(this.h=!!b,Td(this,c[1]||"",!0),this.j=Bd(c[2]||""),this.c=Bd(c[3]||"",!0),Ud(this,c[4]),this.a=Bd(c[5]||"",!0),Vd(this,c[6]||"",!0),this.g=Bd(c[7]||"")):(this.h=!!b,this.b=
new Gd(null,0,this.h))};_.Sd.prototype.toString=function(){var a=[],b=this.u;b&&a.push(Rd(b,Qd,!0),":");var c=this.c;if(c||"file"==b)a.push("//"),(b=this.j)&&a.push(Rd(b,Qd,!0),"@"),a.push((0,window.encodeURIComponent)(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.f,null!=c&&a.push(":",String(c));if(c=this.a)this.c&&"/"!=c.charAt(0)&&a.push("/"),a.push(Rd(c,"/"==c.charAt(0)?Od:Pd,!0));(c=this.b.toString())&&a.push("?",c);(c=this.g)&&a.push("#",Rd(c,Md));return a.join("")};
Td=function(a,b,c){a.u=c?Bd(b,!0):b;a.u&&(a.u=a.u.replace(/:$/,""))};Ud=function(a,b){if(b){b=Number(b);if((0,window.isNaN)(b)||0>b)throw Error("g`"+b);a.f=b}else a.f=null};Vd=function(a,b,c){b instanceof Gd?(a.b=b,Ld(a.b,a.h)):(c||(b=Rd(b,Nd)),a.b=new Gd(b,0,a.h))};_.N=function(a,b,c){a.b.set(b,c)};_.Wd=function(a){return a instanceof _.Sd?new _.Sd(a):new _.Sd(a,void 0)};
_.O=function(a,b,c){if(_.t(a))c&&(a=(0,_.r)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,_.r)(a.handleEvent,a);else throw Error("n");return 2147483647<Number(b)?-1:_.l.setTimeout(a,b||0)};
_.Xd=function(a,b){a instanceof _.Sd||(a=_.Wd(a));b instanceof _.Sd||(b=_.Wd(b));var c=a,d=b,e=new _.Sd(c),f=!!d.u;f?Td(e,d.u):f=!!d.j;f?e.j=d.j:f=!!d.c;f?e.c=d.c:f=null!=d.f;var g=d.a;if(f)Ud(e,d.f);else if(f=!!d.a)if("/"!=g.charAt(0)&&(c.c&&!c.a?g="/"+g:(c=e.a.lastIndexOf("/"),-1!=c&&(g=e.a.substr(0,c+1)+g))),c=g,".."==c||"."==c)g="";else if(-1!=c.indexOf("./")||-1!=c.indexOf("/.")){for(var g=0==c.lastIndexOf("/",0),c=c.split("/"),k=[],p=0;p<c.length;){var B=c[p++];"."==B?g&&p==c.length&&k.push(""):
".."==B?((1<k.length||1==k.length&&""!=k[0])&&k.pop(),g&&p==c.length&&k.push("")):(k.push(B),g=!0)}g=k.join("/")}else g=c;f?e.a=g:f=""!==d.b.toString();f?Vd(e,Bd(d.b.toString())):f=!!d.g;f&&(e.g=d.g);return e};_.Yd=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};
var Zd=function(){};Zd.prototype.a=null;var ae;ae=function(){};_.q(ae,Zd);_.$d=new ae;_.be=function(a){_.y(this,a,"h_icr",null)};_.q(_.be,_.x);_.A("h_icr",_.be);
}catch(e){_._DumpException(e)}
try{
_.Sg=function(a){for(var b=a.a.M(),c={},d=0;d<b.length;d++){var e=b[d],f=a.a.get(e);c[e]={value:f.F(),type:f.type(),multiple:f.za,disabled:!f.W,inverse:f.ya,changed:f.ua}}return c};_.Tg=function(a,b){return _.u(b)?a.getElementById(b):b};_.Q=function(a){return _.Tg(window.document,a)};_.Ug=new _.G("a");_.Vg=new _.G("b");_.Wg=new _.G("c");_.Xg=new _.G("d");_.Yg=new _.G("e");_.Zg=new _.G("f");_.$g=new _.G("g");_.ah=new _.G("h");_.pd=new _.G("i");_.bh=new _.G("j");

}catch(e){_._DumpException(e)}
try{
var ch,dh,fh,gh,hh,ih,jh,kh,lh,mh,nh,ph,qh,rh,wh,xh,zh;ch=function(a){return(a=a.a.get("TopMost"))&&a.W?a.F():!0};dh=0;_.eh=function(a){a&&a!=window.chrome.windows.WINDOW_ID_NONE&&window.chrome.windows.update(a,{focused:!0})};fh=function(a){window.chrome.windows.getAll({populate:!0},function(b){for(var c=0;c<b.length;++c){var d=b[c].tabs;if(null!=d)for(var e=0;e<d.length;++e)if(d[e].selected&&d[e].url==a){_.eh(b[c].id);return}}})};
gh=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};hh=function(){return null!=window.navigator.platform.match(/Mac.*/)};ih=function(){return!_.Oc()&&null!=window.navigator.platform.match(/Linux.*/)};jh=function(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+(a[_.ja]||(a[_.ja]=++dh)):b.substr(0,1)+a};
kh=function(a){if(a instanceof _.vb)return a;if("function"==typeof a.Y)return a.Y(!1);if(_.ra(a)){var b=0,c=new _.vb;c.next=function(){for(;;){if(b>=a.length)throw _.ub;if(b in a)return a[b++];b++}};return c}throw Error("d");};lh=function(a,b){return a>b?1:a<b?-1:0};mh=function(a,b){null!=a&&(window.open(a,"winid_"+(new Date).getTime(),b),_.O((0,_.r)(fh,null,a),1E3))};nh=function(a){null!=a&&(a=window.chrome.runtime.getURL("images_4/"+a));return a};
_.oh=function(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d};_.oh.prototype.contains=function(a){return this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height};_.oh.prototype.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
_.oh.prototype.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};ph=[/^https?:\/\/.*.google.com(:[0-9]+)?\/talkgadget\/success/,/^https:\/\/accounts.google.com\/ServiceLogin/];qh=[1E4,12E4,144E5];rh=[200,2E3,3E5];_.sh=function(a,b){_.I.call(this);this.f=a||1;this.b=b||_.l;this.h=(0,_.r)(this.l,this);this.j=(0,_.m)()};_.q(_.sh,_.I);_.sh.prototype.g=!1;_.sh.prototype.a=null;
_.sh.prototype.setInterval=function(a){this.f=a;this.a&&this.g?(this.stop(),_.th(this)):this.a&&this.stop()};_.sh.prototype.l=function(){if(this.g){var a=(0,_.m)()-this.j;0<a&&a<.8*this.f?this.a=this.b.setTimeout(this.h,this.f-a):(this.a&&(this.b.clearTimeout(this.a),this.a=null),_.M(this,"tick"),this.g&&(this.a=this.b.setTimeout(this.h,this.f),this.j=(0,_.m)()))}};_.th=function(a){a.g=!0;a.a||(a.a=a.b.setTimeout(a.h,a.f),a.j=(0,_.m)())};
_.sh.prototype.stop=function(){this.g=!1;this.a&&(this.b.clearTimeout(this.a),this.a=null)};_.sh.prototype.v=function(){_.sh.B.v.call(this);this.stop();delete this.b};var uh=function(a){this.a=a||_.l.document||window.document};uh.prototype.contains=_.Yd;_.Rf=function(a,b){this.width=a;this.height=b};_.Rf.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
_.Rf.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var vh=function(a){this.a=new _.C;if(a){a=_.yb(a);for(var b=a.length,c=0;c<b;c++){var d=a[c];this.a.set(jh(d),d)}}};_.h=vh.prototype;_.h.ba=function(){return this.a.ba()};_.h.removeAll=function(a){a=_.yb(a);for(var b=a.length,c=0;c<b;c++)this.remove(a[c])};_.h.remove=function(a){return this.a.remove(jh(a))};_.h.clear=function(){this.a.clear()};
_.h.contains=function(a){a=jh(a);return _.xb(this.a.b,a)};_.h.G=function(){return this.a.G()};_.h.Y=function(){return this.a.Y(!1)};wh=function(a,b){if(_.ra(a))try{(0,_.za)(a,b,void 0)}catch(c){if(c!==_.ub)throw c;}else{a=kh(a);try{for(;;)b.call(void 0,a.next(),void 0,a)}catch(c){if(c!==_.ub)throw c;}}};xh=function(a,b,c){a.a||(a.a={});c=c||[];for(var d=[],e=0;e<c.length;e++)d[e]=_.qb(c[e]);a.a[b]=c;_.L(a,b,d)}; _.yh=function(a,b,c){a.a||(a.a={});if(!a.a[c]){for(var d=_.z(a,c),e=[],f=0;f<d.length;f++)e[f]=new b(d[f]);a.a[c]=e}b=a.a[c];b==_.pb&&(b=a.a[c]=[]);return b};zh=function(a,b){a.sort(b||lh)};
var Ah=function(){_.D.call(this)};_.q(Ah,_.D);Ah.prototype.T=function(){};new Ah;var Ch=function(a,b,c){_.I.call(this);this.a=(new uh(b)).a.createElement("IFRAME");b.body.appendChild(this.a);this.a.src=a;c&&(this.a.id=c,this.a.name=c);a=new _.H(this);_.F(this,a);_.xd(_.xd(a,this.a,"load",this.f),this.a,"error",Bh).listen(b.defaultView,"focus",this.b).listen(b.body,"focus",this.b)};_.q(Ch,_.I);Ch.prototype.b=function(){_.lc(this.a.focus,this.a)};Ch.prototype.f=function(){this.b()};Ch.prototype.v=function(){this.a.parentElement.removeChild(this.a);this.a=null;Ch.B.v.call(this)};
var Dh={},Eh=function(){delete Dh.Z},Bh=function(){Dh.Z(1)};_.Fh=function(a){this.c=a;this.a=new _.Vc;this.b=a.get(_.ah);this.a.setItem(new _.Tc("StartOnBrowserLaunch",!0,!1,!1));_.Wc&&this.a.setItem(new _.Tc("TopMost",!0));a=new _.Tc("StopOnBrowserClose",!1,!1,!1);a.setEnabled(!1);this.a.setItem(a);a=new _.Tc("TrayIcon",!0,!1,!1);a.setEnabled(null!=window.navigator.platform.match(/Win.*/)||ih()||hh());this.a.setItem(a);(a=this.b.get("settings"))&&_.Uc(this.a,a);this.b.set("settings",_.Sg(this.a))};_.na("ace.core.SettingsManager",_.Fh);
var Gh=window.chrome.runtime&&window.chrome.runtime.getURL&&window.chrome.runtime.getURL("settingsdialog.html")||"";_.Fh.prototype.Hb=function(){this.b.set("settings",_.Sg(this.a));var a=_.T.g("setting");if(a&&0!=a.length)Hh(a[0],"focus");else{var a=Math.floor((window.screen.height-200)/2),b=Math.floor((window.screen.width-520)/2),c=["width=520"];c.push("height=200");c.push("top="+a);c.push("left="+b);c.push("location=no");mh(Gh,c.join(","))}};_.Fh.prototype.launchSettingsDialog=_.Fh.prototype.Hb;
_.Fh.prototype.jc=function(){var a=new _.Vc(_.Sg(this.a)),b=this.b.get("settings");_.Uc(this.a,b);var c=new _.Vc(b),b=c.getItem("StopOnBrowserClose"),a=a.getItem("TrayIcon"),c=c.getItem("TrayIcon");a.W&&(c.F()||b.F()?(b=this.c.get(_.Vg),Ih(b),Jh(b)):c.F()||b.F()||Kh(this.c.get(_.Vg)))};_.Fh.prototype.updateSettingsFromStorage=_.Fh.prototype.jc;_.Fh.prototype.Wa=function(){var a=_.T.g("setting");if(a)for(var b=0;b<a.length;++b)Hh(a[b],"close")};_.Fh.prototype.closeUI=_.Fh.prototype.Wa; var Hh=function(a,b){var c=new _.J;_.Rc(c,b);_.Sc(c,[]);_.T.b(a).sendMessage(c)};
var Qh=function(a,b){_.H.call(this);this.b=a;_.Nc("viewer",""+(new Date).getTime());this.g=this.h=null;this.w=_.T;this.D=(0,_.m)();this.l=a.get(_.Vg);var c=a.get(_.Zg),d=window.chrome.i18n.getMessage("CHROME_HANGOUTS_SHORT_NAME"),e=nh("viewer-14.png"),f=nh("viewer-28.png"),d=Lh(c,"viewer","viewer","viewer.html?viewer",d,e,f),e=b?_.zd(b,_.Mh,2).ha():null,e=Nh(c,new _.Rf(260,460),!0,e);Oh(c,d.id,e);this.a=d;this.a.onClosed.addListener((0,_.r)(this.N,this));Ph(this.a,(0,_.r)(this.A,this))};_.q(Qh,_.H);
Qh.prototype.v=function(){this.b.c(_.pd)==this&&this.b.I();this.removeAll();Qh.B.v.call(this)};var Rh=function(a){_.E(a.h);a.h=null;_.E(a.g);a.g=null;_.Tg(a.c.a,"retryInfo").style.display="none"};Qh.prototype.close=function(){_.E(this.a);this.b.c(_.pd)==this&&this.b.I()};
Qh.prototype.A=function(){this.c=new uh(Sh(this.a).document);this.a.setTitle(window.chrome.i18n.getMessage("CHROME_HANGOUTS_SHORT_NAME"));_.Tg(this.c.a,"retryMessage").textContent=window.chrome.i18n.getMessage("CHROME_EXT_CANNOT_CONNECT");var a=_.Tg(this.c.a,"retryLink");a.textContent=window.chrome.i18n.getMessage("QUASAR_TRY_NOW");this.listen(a,"click",this.C);this.listen(this.w,"onStatusChange",this.j);this.j()};Qh.prototype.C=function(a){a.c();this.b.get(_.Ug).g()};
Qh.prototype.j=function(){switch(this.l.a){case 3:if(!this.h){Rh(this);var a=this.b.get(_.$g).a,a=_.Xd(a.b[0],"/talkgadget/qsignin");_.N(a,"passive","1");_.N(a,"hl",window.chrome.i18n.getMessage("@@ui_locale"));this.h=new Ch(a.toString(),this.c.a)}break;case 2:Rh(this);break;case 6:Rh(this);_.Tg(this.c.a,"retryInfo").style.display="block";break;default:Th(this)}};var Th=function(a){a.g||(Rh(a),a.b.get(_.Ug).L.b.then(function(a){this.g=new Ch(a,this.c.a,"popoutRoster")},void 0,a))};
var Uh=function(a,b){this.b=_.Ed(a);this.a=0;this.c=b||!1};Uh.prototype.reset=function(){this.a=0};Uh.prototype.F=function(a){var b=this.b[this.a],b=(.5+1*Math.random())*b;a&&Vh(this);return b};var Vh=function(a){a.c&&a.a==a.b.length-1||a.a++};var Wh=function(a,b,c){_.D.call(this);this.b=a;this.f=b||0;this.c=c;this.Z=(0,_.r)(this.g,this)};_.q(Wh,_.D);Wh.prototype.a=0;Wh.prototype.v=function(){Wh.B.v.call(this);this.stop();delete this.b;delete this.c};var Xh=function(a,b){a.stop();a.a=_.O(a.Z,_.n(b)?b:a.f)};Wh.prototype.stop=function(){0!=this.a&&_.l.clearTimeout(this.a);this.a=0};Wh.prototype.g=function(){this.a=0;this.b&&this.b.call(this.c)};
var Yh=function(a,b,c){_.D.call(this);this.c=null!=c?(0,_.r)(a,c):a;this.b=b;this.Z=(0,_.r)(this.Tb,this);this.a=[]};_.q(Yh,_.D);_.h=Yh.prototype;_.h.sa=!1;_.h.da=null;_.h.Ya=function(a){this.a=arguments;this.da?this.sa=!0:Zh(this)};_.h.stop=function(){this.da&&(_.l.clearTimeout(this.da),this.da=null,this.sa=!1,this.a=[])};_.h.v=function(){Yh.B.v.call(this);this.stop()};_.h.Tb=function(){this.da=null;this.sa&&(this.sa=!1,Zh(this))};var Zh=function(a){a.da=_.O(a.Z,a.b);a.c.apply(null,a.a)};
_.V=function(a){_.H.call(this);this.h=a;this.b=a.get(_.Vg);this.O=a.c(_.Zg);this.L=_.Dc();this.w=null;this.H=new Yh(this.g,6E4,this);_.F(this,this.H);Dh.Z=(0,_.r)(this.Nb,this);_.zb(this,Eh);this.j=!1;this.A=new Uh(qh,!0);this.J=new Wh(this.bc,this.A.F(),this);_.F(this,this.J);this.l=new Wh(this.cb,4E4,this);_.F(this,this.l);this.listen(window,"online",this.Qb);this.a=new Uh(rh);this.c=new Wh(this.yb,this.a.F(),this);_.F(this,this.c);window.chrome.cookies.onChanged.addListener((0,_.r)(this.P,this));
this.D=(0,_.r)(this.mb,this);this.C=(0,_.r)(this.lb,this);window.chrome.tabs.onUpdated.addListener(this.D);window.chrome.tabs.onCreated.addListener(this.C)};_.q(_.V,_.H);_.na("ace.core.DataChannelManager",_.V);_.V.prototype.v=function(){window.chrome.tabs.onCreated.removeListener(this.C);window.chrome.tabs.onUpdated.removeListener(this.D);delete this.C;delete this.D;_.E(this.w);_.V.B.v.call(this)};
_.V.prototype.ta=function(a,b){_.$h(this);a:{var c=this.h,d=c.c(_.pd);if(d){if(ai(d.a)?!bi(d.a):1E3>(0,_.m)()-d.D){d.a.focus();break a}d.close()}d=new Qh(c,b);c.a(_.pd,d,!0)}};_.V.prototype.showViewer=_.V.prototype.ta;_.V.prototype.hc=function(a,b){this.L.a(b||"")};_.V.prototype.setRosterUrl=_.V.prototype.hc;_.V.prototype.Ba=function(){this.b.$(0,1);var a=this.h.c(_.pd);a&&a.close();ci(this);this.j=!1};_.V.prototype.terminateApplication=_.V.prototype.Ba;
_.$h=function(a){a.j||(a.listen(_.T,"onStatusChange",a.nb),a.g(),a.h.get(_.$g),a.j=!0)};_.V.prototype.g=function(){this.K||(this.b.$(0,2),ci(this),this.w=new Ch(window.chrome.runtime.getURL("datachannel.html"),window.document,"centralRoster"))};var ci=function(a){a.O.va();a.h.get(_.Yg).na();_.E(a.w);a.w=null;a.L=_.Dc()},ei=function(a,b){var c=a.h.get(_.$g).a.b[0];window.chrome.cookies.getAll({url:c},(0,_.r)(function(a){a=a&&di("SID",a)&&di("SSID",a)&&di("SAPISID",a);b(a)},a))};
_.V.prototype.U=function(a){var b=this.b.a;if(a){if(3==b){if(a=0==this.c.a)a=this.a,a=a.a<a.b.length;a&&Xh(this.c,this.a.F())}}else 3!=b&&this.g()};_.V.prototype.P=function(a){"SSID"!=a.cookie.name&&"SAPISID"!=a.cookie.name||".google.com"!=a.cookie.domain||ei(this,(0,_.r)(this.U,this))};var di=function(a,b){return(0,_.Ca)(b,function(b){var d=b.expirationDate&&b.expirationDate<(0,_.m)()/1E3;return b.name==a&&".google.com"==b.domain&&!d})};_.h=_.V.prototype;
_.h.nb=function(){this.J.stop();this.l.stop();switch(this.b.a){case 2:Xh(this.l);break;case 6:Xh(this.J,this.A.F());break;case 4:case 9:case 8:case 5:this.A.reset(),this.c.stop()}};_.h.Qb=function(){4!=this.b.a&&this.H.Ya()};_.h.bc=function(){Vh(this.A);this.g()};_.h.Nb=function(a){ci(this);switch(a){case 1:this.cb();break;case 2:this.H.Ya()}};_.h.cb=function(){this.K||(this.l.stop(),this.b.$(0,6))};_.h.yb=function(){Vh(this.a);ei(this,(0,_.r)(function(a){a&&this.g()},this))}; _.h.mb=function(a,b){b.url&&fi(this,b.url)};_.h.lb=function(a){a.url&&fi(this,a.url)};var fi=function(a,b){(0,_.Ca)(ph,function(a){return a.test(b)})&&0!=a.a.a&&(a.a.reset(),0!=a.c.a&&Xh(a.c,a.a.F()))};
_.W=function(a){this.A=a;this.w=a.get(_.$g);this.b=a.get(_.ah);this.a=1;this.f=this.j=null;this.g=this.c=!1;this.l=(0,_.r)(this.C,this);Ih(this);Jh(this);this.b.has("UnreadIndicator")&&this.b.remove("UnreadIndicator");this.b.has("app_status")&&this.b.remove("app_status");this.b.has("user_id")&&this.b.remove("user_id");this.b.has("client_state")&&this.b.remove("client_state")};_.q(_.W,_.D);_.na("ace.core.DesktopManager",_.W);_.W.prototype.v=function(){Kh(this);_.W.B.v.call(this)};
_.W.prototype.$=function(a,b){this.a!=b&&(this.a=b,Jh(this),gi(this),1==this.a&&(this.f=this.j=null,this.g=this.c=!1,Kh(this),this.w.Wa(),this.A.get(_.Yg).na()),_.T.j())};_.W.prototype.changeDesktop=_.W.prototype.$;_.W.prototype.fc=function(a,b){this.c!=b&&(this.c=b,Jh(this),gi(this))};_.W.prototype.setMainUiShowing=_.W.prototype.fc;_.W.prototype.h=function(){return this.c};
var Ih=function(a){var b=a.w.a,c;if(c=null!=window.navigator.platform.match(/Win.*/)||ih()||hh())c=b.a.get("StopOnBrowserClose"),(c=c&&c.W?c.F():!1)||(c=(b=b.a.get("TrayIcon"))&&b.W?b.F():!1);c&&window.chrome.systemIndicator&&(window.chrome.systemIndicator.enable(),window.chrome.systemIndicator.onClicked.addListener(a.l))},Kh=function(a){window.chrome.systemIndicator&&(window.chrome.systemIndicator.disable(),window.chrome.systemIndicator.onClicked.removeListener(a.l))},gi=function(a){var b;switch(a.a){case 2:b=
window.chrome.i18n.getMessage("QUASAR_TIP_CONNECTING");break;case 3:b=window.chrome.i18n.getMessage("QUASAR_TIP_NOT_LOGIN");break;case 4:case 9:case 8:b=a.c?a.g?window.chrome.i18n.getMessage("CHROME_EXT_TIP_CONNECTED_MISSED_MESSAGES"):window.chrome.i18n.getMessage("QUASAR_TIP_CONNECTED"):window.chrome.i18n.getMessage("QUASAR_TIP_NOT_LOGIN");break;case 6:b=window.chrome.i18n.getMessage("QUASAR_TIP_NOT_LOAD");break;default:b=window.chrome.i18n.getMessage("QUASAR_TIP_DISCONNECTED")}a=a.f?"\n"+a.f:"";
(b=window.chrome.i18n.getMessage("CHROME_HANGOUTS_SHORT_NAME")+a+"\n"+b)&&window.chrome.browserAction.setTitle({title:b})};_.W.prototype.kc=function(a,b,c){1!=this.a&&(a=b||window.chrome.i18n.getMessage("QUASAR_MENUTEXT_UNKNOWN_USER"),a!=this.j&&(this.j=a),this.f=c)};_.W.prototype.updateUserName=_.W.prototype.kc;_.W.prototype.ic=function(a,b){this.g!=b&&(this.g=b,Jh(this),gi(this))};_.W.prototype.setUnreadIndicator=_.W.prototype.ic;
var Jh=function(a){window.chrome.browserAction.setIcon(hi(a,!0));window.chrome.systemIndicator&&window.chrome.systemIndicator.setIcon(hi(a))},ii=function(a){switch(a.a){case 2:return"offline_working";case 4:case 9:case 8:return a.c?a.g?"available_missed":"available":"offline";case 6:return"offline_unknown";default:return"offline"}},hi=function(a,b){var c=!b&&hh()?"_mac_":"_",d=ii(a),e=window.chrome.runtime.getURL("images_4/presence/"+d+c+"19.png"),c=window.chrome.runtime.getURL("images_4/presence/"+ d+c+"38.png");return{path:{19:e,38:c}}};_.W.prototype.C=function(){var a=_.T.a();a.ia();a.b("onTrayClick",[1])};
var ji=function(a,b){this.a=a;this.j=b;this.l=window.chrome.runtime.getURL("images_4/icon-128x128.png");this.f=this.h=this.w="";this.u=0;this.b=[];this.g=""},ki=function(a){this.name=a;this.title=""};ji.prototype.setTitle=function(a){a&&(this.w=a)};
var li=function(a){var b=a.w;a.h&&(b+=" "+a.h);var c=(a.f||7!=a.j?a.f||"":window.chrome.i18n.getMessage("CHROME_EXT_ONEONONE_PLUS_HANGOUT_DETAILS")).replace(/^(\<br\>)+/,""),d=(0,_.Ba)(a.b,function(a){var b;if(!(b=a.title))a:{switch(a.name){case "join hangout":b=window.chrome.i18n.getMessage("QUASAR_ANSWER_BUTTON_TEXT");break a;case "ignore":b=window.chrome.i18n.getMessage("QUASAR_DECLINE_BUTTON_TEXT");break a}b=""}return{title:b}},a);return{type:"basic",iconUrl:a.l,title:b,message:c,buttons:d,priority:2}};
var mi=function(){this.b=new _.C;this.a=new _.sh(18E5);_.Sb(this.a,"tick",(0,_.r)(this.c,this,this.b,0,200));_.th(this.a)};_.q(mi,_.D);mi.prototype.v=function(){this.a.N()};var ni=function(a,b){var c=null!=b.c?b.a+b.c:null;return null!=c?_.xb(a.b.b,c):!1};
mi.prototype.c=function(a,b,c){var d=a.ba();if(0!=d){var e=0;null!=b&&0<b&&(e=b<d?b:d);b=d;null!=c&&c<d&&(b=0<c?c:0);e>b&&(e=b);var f=[];c=a.Y(!0);wh(c,function(b){f.push([b,a.get(b)])});f.sort(function(a,b){return a[1]-b[1]});if(31536E7<f[d-1][1]-f[0][1])a.clear();else{c=0;b=d-b;for(var d=d-e,e=(0,_.m)(),g=0;g<f.length;++g)if(c<b||c<d&&f[g][1]<=e)a.remove(f[g][0]),c+=1;else break}}};
var oi=function(a){_.y(this,a,"acr:bcr",null)};_.q(oi,_.x);_.A("acr:bcr",oi);var pi=function(a){_.y(this,a,"acr:srs",null)};_.q(pi,_.x);_.A("acr:srs",pi);var qi=function(a){_.y(this,a,"acr:rss",null)};_.q(qi,_.x);_.A("acr:rss",qi);var ri=function(a){_.y(this,a,"acr:rrs",null)};_.q(ri,_.x);_.A("acr:rrs",ri);var si=function(a){_.y(this,a,"acr:rsr",null)};_.q(si,_.x);_.A("acr:rsr",si);_.ui=function(a){_.y(this,a,"acr:wrs",ti)};_.q(_.ui,_.x);var ti=[1];_.A("acr:wrs",_.ui); var vi=function(a){_.y(this,a,0,null)};_.q(vi,_.x);vi.prototype.S=function(){return _.z(this,2)};vi.prototype.ga=function(){return _.z(this,11)};
var zi;_.xi=function(a){_.y(this,a,"acq:rs",wi)};_.q(_.xi,_.x);var wi=[3];_.A("acq:rs",_.xi);var yi=function(a){_.y(this,a,0,null)};_.q(yi,_.x);yi.prototype.getState=function(){return _.z(this,6)};_.Mh=function(a){_.y(this,a,0,null)};_.q(_.Mh,_.x);_.Mh.prototype.ha=function(){return _.zd(this,yi,1)};zi=function(a,b){_.yd(a,1,b)};_.Ai=function(a){_.y(this,a,0,null)};_.q(_.Ai,_.x);_.Ai.prototype.S=function(){return _.z(this,1)};var Bi=function(a,b){_.L(a,1,b)}; _.Ai.prototype.ha=function(){return _.zd(this,yi,2)};var Ci=function(a,b){_.yd(a,2,b)};_.Ai.prototype.ga=function(){return _.z(this,3)};var Di=function(a,b){_.L(a,3,b)};
var Ei,Ii,Hi;Ei=function(a){this.c=a;this.a={};this.b=a.get(_.ah)};_.Fi=function(a,b){return(null!=a?a:"null")+"-"+(null!=b?b:"null")};
Ii=function(a,b){_.O(a.reload,6E4,a);var c=[],d={},e=a.c.get(_.Zg),f=_.yh(b,vi,1)||[];(0,_.za)(f,function(a){c.push(_.z(a,1));var b=_.Fi(a.S(),a.ga());d[b]=a});var g=c.length;c.push("viewer");Gi(e,c,(0,_.r)(function(a){for(var c=[],e=0;e<f.length;e++){var K=a[e];if(K){var Ra=f[e],U=new _.Ai;Di(U,Ra.ga());Bi(U,Ra.S());Ci(U,Hi(K));c.push(U)}}zh(c,function(a,b){return _.z(b.ha(),2)-_.z(a.ha(),2)});(0,_.za)(c,function(a,b){var c=_.Fi(a.S(),a.ga());_.L(d[c],3,b)});a=a[g];e=new _.xi;a&&(K=new _.Mh,zi(K,
Hi(a)),_.yd(e,2,K));xh(e,3,c);xh(b,1,f);_.yd(e,1,b);this.b.set("ReloadState",_.qb(e));_.T.a().b("eventReloadStateSaved",[])},a))};Hi=function(a){var b=new yi;_.L(b,1,a.top);_.L(b,2,a.left);_.L(b,3,a.width);_.L(b,4,a.height);_.L(b,5,a.focused);_.L(b,6,a.state);_.L(b,7,a.alwaysOnTop);return b};Ei.prototype.read=function(){var a=this.f;this.f=null;_.T.a().b("eventReloadStateRead",[a&&_.qb(a)||null])};Ei.prototype.reload=function(){window.chrome.runtime.reload()};
_.X=function(a){this.a=new Ei(a);this.b=a;window.chrome.runtime.onUpdateAvailable.addListener((0,_.r)(this.f,this))};_.na("ace.core.ExtensionLibrary",_.X);_.X.prototype.f=function(){_.T.a().b("eventReloadClient",[]);_.O(this.a.reload,864E5+288E5*Math.random(),this.a)};_.X.prototype.dc=function(a,b,c,d){a=_.T.b(b);null!=a&&_.n(d)&&d&&(d=a.j,null!=d&&null!=d.id&&(window.chrome.tabs.update(d.id,{selected:!0}),c&&window.chrome.tabs.get(d.id,function(a){_.eh(a.windowId)})))};_.X.prototype.selectTab=_.X.prototype.dc;
_.X.prototype.Wb=function(a,b,c){c?mh(b,"width=500,height=400"):window.chrome.tabs.create({url:b,selected:!0},function(a){null!=a?_.O(function(){window.chrome.tabs.get(a.id,function(a){_.eh(a.windowId)})},2E3):mh(b)})};_.X.prototype.openUrl=_.X.prototype.Wb;_.X.prototype.Cb=function(a,b){this.c=this.b.get(_.Zg);this.c.focus(b)};_.X.prototype.focusMoleByFrameId=_.X.prototype.Cb;_.X.prototype.ia=function(){_.T.a().ia()};_.X.prototype.showApplication=_.X.prototype.ia;
_.X.prototype.cc=function(a,b){var c=new _.ui(b);Ii(this.a,c)};_.X.prototype.saveReloadState=_.X.prototype.cc;_.X.prototype.Xb=function(){this.a.read()};_.X.prototype.readReloadState=_.X.prototype.Xb;_.X.prototype.ac=function(){this.a.reload()};_.X.prototype.reloadExtension=_.X.prototype.ac;
_.X.prototype.$b=function(a,b){window.chrome.tabs.create({url:"https://chrome.google.com/webstore/detail/"+(b?b:window.chrome.runtime.id),selected:!0},(0,_.r)(function(){window.chrome.management.uninstallSelf()},this))};_.X.prototype.reinstall=_.X.prototype.$b;_.X.prototype.Aa=function(){_.T.a().Aa()};_.X.prototype.onHostReady=_.X.prototype.Aa;
var Ji=function(a,b){if(a)this.focused=a.focused,this.alwaysOnTop=a.alwaysOnTop,this.top=a.top,this.left=a.left,this.width=a.width,this.height=a.height,this.state=a.state;else if(b){this.focused=b.contentWindow.document.hasFocus();this.alwaysOnTop=b.isAlwaysOnTop();var c=b.getBounds();this.top=c.top;this.left=c.left;this.width=c.width;this.height=c.height;this.state=b.isMinimized()?"minimized":"normal"}else this.alwaysOnTop=this.focused=!1,this.height=this.width=this.left=this.top=0,this.state=""}; Ji.prototype.isMinimized=function(){return"minimized"==this.state};
var Ki=function(a,b,c){this.a=c||new Ji;c||(this.a.alwaysOnTop=ch(a.get(_.$g).a))};Ki.prototype.getProperties=function(){return this.a};var Mi=function(a,b,c){(b=b.g)?Li(a.get(_.Zg),b,function(b){c(new Ki(a,0,b))}):c(new Ki(a))};_.Y=function(a){_.D.call(this);this.j=a;this.a=new _.C;this.h=new _.C;this.b=new mi;_.F(this,this.b);this.g=(0,_.r)(this.Kb,this);window.chrome.notifications.onClosed.addListener(this.g);this.c=(0,_.r)(this.ob,this);window.chrome.notifications.onClicked.addListener(this.c);this.f=(0,_.r)(this.Jb,this);window.chrome.notifications.onButtonClicked.addListener(this.f)};_.q(_.Y,_.D);_.na("ace.core.NotificationManager",_.Y);
_.Y.prototype.v=function(){_.za(this.a.G(),_.E);this.a.clear();window.chrome.notifications.onClosed.removeListener(this.g);window.chrome.notifications.onClicked.removeListener(this.c);window.chrome.notifications.onButtonClicked.removeListener(this.f);_.Y.B.v.call(this)};
_.Y.prototype.Zb=function(a,b){var c;if(b&&b.Content){c=[b.Id.ServiceUrl,b.Id.ServiceId].join(";");0==c.indexOf("bc")?c=new ji(c,2):0==c.indexOf("hangout")?(c=new ji(c,7),c.b.push(new ki("join hangout")),c.b.push(new ki("ignore"))):c=void 0;c.setTitle(b.Content.TitleText);c.h=b.Content.SubtitleText;c.f=b.Content.BodyText;c.c=b.Content.BodyTextId;var d=0;b.Content.EndTimeMs&&(d=b.Content.EndTimeMs,(0,window.isNaN)(d)||!(0,window.isFinite)(d))&&(d=0);d=d||(0,_.m)()+1E4;c.u=d;if(b.Content.ServiceIcon){var d=
c,e=b.Content.ServiceIcon;e&&(0==e.indexOf("images_4/")&&(e=window.chrome.runtime.getURL(e)),d.l=e)}b.Content.FrameId&&(c.g=b.Content.FrameId)}else c=null;c&&(_.T.a().b("eventReportImpression",[193]),ni(this.b,c)||(d=this.b,e=null!=c.c?c.a+c.c:null,null!=e&&!ni(d,c)&&d.b.set(e,(0,_.m)()+18E5),Ni(this,c)))};_.Y.prototype.registerNotification=_.Y.prototype.Zb;
var Ni=function(a,b){2==b.j||b.g?Mi(a.j,b,function(c){c=c.getProperties();c.focused||c.alwaysOnTop||Oi(a,b)}):Oi(a,b)},Oi=function(a,b){var c=b.a,d=b.u-(0,_.m)();0>=d?a.Za(c):(a.a.set(c,b),window.chrome.notifications.create(c,li(b),function(){_.T.a().b("eventReportImpression",[192])}),_.l.clearTimeout(a.h.get(c,null)),b.u!=Number.MAX_VALUE&&a.h.set(c,_.O((0,_.r)(a.Za,a,c),d)),_.T.a().b("eventReportImpression",[194]))};_.Y.prototype.na=function(){(0,_.za)((0,_.Aa)(this.a.G(),_.tb),this.fa,this)};
_.Y.prototype.cleanAllNotifications=_.Y.prototype.na;_.Y.prototype.wb=function(a,b){var c=this.a.get(b);c&&this.fa(c)};_.Y.prototype.cleanANotification=_.Y.prototype.wb;_.h=_.Y.prototype;_.h.fa=function(a){a=a.a;window.chrome.notifications.clear(a,_.ta);this.a.remove(a)};_.h.Kb=function(a,b){b&&this.a.get(a)&&(this.a.remove(a),Pi(a,"toastEventOnClose"))};_.h.ob=function(a){var b=this.a.get(a);b&&(Pi(a,"toastEventOnBody"),this.fa(b))};
_.h.Jb=function(a,b){var c=this.a.get(a);c&&(Pi(a,"toastEventOnButton",c.b[b].name),this.fa(c))};_.h.Za=function(a){var b=this.a.get(a);b&&(Pi(a,"toastEventOnTimeout"),this.fa(b))};var Pi=function(a,b,c){var d=_.T;(d=d&&d.a())&&!d.K&&_.T.a().b(b,[a,c,"",!1])};
var Qi=function(){_.D.call(this);this.a=new vh};_.q(Qi,_.D);Qi.prototype.X=function(a){var b,c=Array.prototype.slice.call(arguments);(0,_.za)(this.a.G(),function(a){b=a.apply(null,c)});return b};Qi.prototype.addListener=function(a){this.a.a.set(jh(a),a)};Qi.prototype.removeListener=function(a){this.a.remove(a)};Qi.prototype.v=function(){this.a.clear();Qi.B.v.call(this)};
var Ri=function(a){return(a=a.exec(_.Ea))?a[1]:""};(function(){if(_.hb)return Ri(/Firefox\/([0-9.]+)/);if(_.w||_.Ta||_.Qa)return _.cb;if(_.lb)return Ri(/Chrome\/([0-9.]+)/);if(_.mb&&!(_.La()||_.v("iPad")||_.v("iPod")))return Ri(/Version\/([0-9.]+)/);if(_.ib||_.jb){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.Ea);if(a)return a[1]+"."+a[2]}else if(_.kb)return(a=Ri(/Android\s+([0-9.]+)/))?a:Ri(/Version\/([0-9.]+)/);return""})();
var Ui=function(){_.D.call(this);this.b=[];this.j=new Qi;_.F(this,this.j);this.g=new Qi;_.F(this,this.g);this.onClosed=new Qi;this.h=!1;this.c=null;this.l=(0,_.r)(this.J,this);Si.addListener(this.l);this.w=(0,_.r)(this.H,this);Ti.addListener(this.w)};_.q(Ui,_.D);Ui.prototype.v=function(){bi(this)||void 0!=this.a&&window.chrome.windows.remove(this.a);Vi(this);this.l&&(Si.removeListener(this.l),Ti.removeListener(this.w));_.E(this.onClosed);Ui.B.v.call(this)};
var Si=window.chrome.windows&&window.chrome.windows.onRemoved,Ti=window.chrome.windows&&window.chrome.windows.onFocusChanged;Ui.prototype.create=function(a){window.chrome.windows.create(a,(0,_.r)(function(a){this.K?window.chrome.windows.remove(a.id):(this.a=a.id,Wi(this))},this))};
var Wi=function(a){if(null!=a.b&&ai(a))if(bi(a))Vi(a);else{for(;a.b.length&&!bi(a);)a.b.shift()(a);a.b=null}},ai=function(a){return!(!_.qa(a.a)||!a.f)},Ph=function(a,b){bi(a)?Vi(a):null==a.b?b(a):a.b.push(b)},bi=function(a){return!(!a.f||!a.f.closed)};Ui.prototype.J=function(){bi(this)&&Vi(this)};var Vi=function(a){if(!a.h){var b=a.onClosed;a.onClosed=new Qi;_.O((0,_.r)(function(){this.h||(this.h=!0,b.X(this));_.E(b)},a))}};
Ui.prototype.H=function(a){if(a!=this.a){if(null===this.c||this.c)this.c&&(this.c=!1),this.g.X(this)}else this.c=!0,this.j.X(this)};var Sh=function(a){var b;b=a.a?a.f:null;return!b||bi(a)?null:b};_.h=Ui.prototype;_.h.isMinimized=function(){return this.D.isMinimized()};_.h.isMaximized=function(){return this.D.isMaximized()};_.h.minimize=function(){Ph(this,(0,_.r)(function(){window.chrome.windows.update(this.a,{state:"minimized"})},this))};
_.h.focus=function(){Ph(this,(0,_.r)(function(){window.chrome.windows.update(this.a,{focused:!0})},this))};_.h.drawAttention=function(a){Ph(this,(0,_.r)(function(){window.chrome.windows.update(this.a,{drawAttention:a})},this))};_.h.getProperties=function(a){Ph(this,_.oa(Xi,[this],function(b){a(b[0])}))}; var Xi=function(a,b){window.chrome.windows.getAll(function(c){var d={};(0,_.za)(c,function(a){d[a.id]=a});var e=[];(0,_.za)(a,function(a){var b;a&&ai(a)&&!bi(a)&&(b=d[a.a]);var c;b&&(c=new Ji(b));e.push(c)});b(e)})};
var Yi=function(){Ui.call(this)};_.q(Yi,Ui);Yi.prototype.setTitle=function(a){Ph(this,(0,_.r)(function(){Sh(this).document.title=a},this))};
var $i=function(a,b){a.C=b;Ph(a,(0,_.r)(function(){Zi(this)},a))},aj=function(a,b){a.I=b;Ph(a,(0,_.r)(function(){Zi(this)},a))},Zi=function(a){var b=Sh(a).document,c=new uh(b),b=b.querySelector("HEAD"),d=b.querySelectorAll("link[rel='shortcut icon']"),e=nh("icon-24x24.png");a=[a.C||e,a.I];for(var e=_.Oc()?2:1,f="",g=0;g<e;++g)if(a[g]&&a!=f){var f=a[g],k=d[g];k||(k=c.a.createElement("LINK"),b.appendChild(k));k.rel="shortcut icon";var p=a[g];k.type=gh(p,".ico")?"image/x-icon":gh(p,".gif")?"image/gif": "image/png";k.href=a[g]}};
var dj,ej;_.cj=function(a){this.a={};if(a)for(var b=0;b<a.length;b++)this.a[_.bj(a[b])]=null};dj={};_.bj=function(a){return a in dj||32==String(a).charCodeAt(0)?" "+a:a};ej=function(a){return 32==a.charCodeAt(0)?a.substr(1):a};_.h=_.cj.prototype;_.h.clear=function(){this.a={}};_.h.contains=function(a){return _.bj(a)in this.a};_.h.forEach=function(a,b){for(var c in this.a)a.call(b,ej(c),void 0,this)};
_.h.ba=Object.keys?function(){return Object.keys(this.a).length}:function(){var a=0,b;for(b in this.a)a++;return a};_.h.G=Object.keys?function(){return Object.keys(this.a).map(ej,this)}:function(){var a=[],b;for(b in this.a)a.push(ej(b));return a};_.h.remove=function(a){a=_.bj(a);return a in this.a?(delete this.a[a],!0):!1};_.h.Y=function(){return kh(this.G())};
_.Z=function(a){_.D.call(this);this.f=a;this.a={};this.c={};this.b=new _.cj;_.na("__onPanelLoad",(0,_.r)(this.A,this));this.h=a.get(_.Vg);a=new _.H(this);_.F(this,a);a.listen(_.T,"onStatusChange",this.j)};_.q(_.Z,_.D);_.na("ace.core.PanelsManager",_.Z);_.Z.prototype.v=function(){for(var a in this.a)this.ra(this.a[a]);_.Z.B.v.call(this)};
_.Z.prototype.isMaximized=function(a,b){var c=function(a){a=a?!a.isMinimized():null;_.T.a().b("eventIsMinimizedResponse",[b,a])},d=this.a[b];d?d.getProperties(c):c(void 0)};_.Z.prototype.isMaximized=_.Z.prototype.isMaximized;
_.Z.prototype.Ub=function(a,b,c,d,e,f,g,k,p,B){a="panel.html?"+b;d=d||window.chrome.i18n.getMessage("CHROME_HANGOUTS_SHORT_NAME");b=Lh(this,b,k||b,a,d,e,g);Ph(b,(0,_.r)(this.g,this,c));c=new _.Rf(280,420);p||B?(p=p||null,e=B||null,B=this.f.get(_.Wg).a,p=_.Fi(p,e),(e=B.a[p])&&delete B.a[p],B=e?e.ha():null):B=null;f=Nh(this,c,!!f,B);Oh(this,b.id,f)};_.Z.prototype.openPanel=_.Z.prototype.Ub;
_.Z.prototype.openDialog=function(a,b,c,d,e,f,g){a="dialog.html?"+b;d=d||window.chrome.i18n.getMessage("CHROME_HANGOUTS_SHORT_NAME");b=Lh(this,b,b,a,d);Ph(b,(0,_.r)(this.g,this,c));c=Nh(this,new _.Rf(f,g),e,null);c.$a=!0;Oh(this,b.id,c);return b};_.Z.prototype.openDialog=_.Z.prototype.openDialog;_.Z.prototype.Vb=function(a,b,c,d,e,f,g){d=d||window.chrome.i18n.getMessage("CHROME_HANGOUTS_SHORT_NAME");a=Lh(this,b,b,c,d);e=Nh(this,new _.Rf(f,g),e,null);e.$a=!0;Oh(this,a.id,e);return a};
_.Z.prototype.openSimplePopup=_.Z.prototype.Vb;var Lh=function(a,b,c,d,e,f,g){a.a[b]&&a.ra(a.a[b]);var k=new Yi;k.id=b;k.key=c;k.url=d;k.setTitle(e);$i(k,f);aj(k,g);a.a[b]=k;a.c[c]=b;return k};_.Z.prototype.g=function(a,b){b.A=new Ch(a,Sh(b).document);_.F(b,b.A)};
var Nh=function(a,b,c,d){b={focus:c,ea:null,width:b.width,height:b.height,minimize:!1};if(d){b.top=_.z(d,1);b.left=_.z(d,2);c=_.z(d,3);var e=_.z(d,4);_.z(d,7)?(b.width=Math.max(b.width,c),b.height=Math.max(b.height,e)):(b.width=c,b.height=e);"minimized"==d.getState()&&(b.minimize=!0);b.ea=_.z(d,7);b.focus=_.z(d,5)}b.ea="boolean"==typeof b.ea?b.ea:ch(a.f.get(_.$g).a);return b},Oh=function(a,b,c){var d=a.a[b];d.onClosed.addListener((0,_.r)(a.ra,a));d.j.addListener((0,_.r)(a.w,a));d.g.addListener((0,_.r)(a.l,
a));c.minimize&&d.minimize();b="panel";c.ea||(b=ih()?"popup":"detached_panel");c.$a&&(b="popup");var e={type:b,url:d.url,focused:c.focus,width:c.width,height:c.height};if(b=null!=c.top&&null!=c.left)e.top=c.top,e.left=c.left;b||c.ea?d.create(e):Gi(a,Object.keys(a.c),(0,_.r)(function(a){var b=window.screen,c;c=new _.Rf(260,460);var p=new _.Rf(280,420);c=new _.Rf(Math.max(c.width,p.width),Math.max(c.height,p.height));for(var B=b.availWidth,K=b.availHeight-50,p=b.availTop+K%c.height,b=b.availLeft+B%
c.width,B=Math.floor(B/c.width),Ra=Math.floor(K/c.height),K=Array(B*Ra),U=0;U<a.length;U++){var R=a[U];if(R){for(var gb=[R.left,R.left+R.width-1],R=[R.top,R.top+R.height-1],S=0;2>S;S++)gb[S]=Math.floor(Math.max(0,gb[S]-b)/c.width),R[S]=Math.floor(Math.max(0,R[S]-p)/c.height);for(S=gb[0];S<=gb[1];S++)for(var Sa=R[0];Sa<=R[1];Sa++)S<B&&Sa<Ra&&(K[S+Sa*B]=1)}}a=K.length-1;for(U=K.length-1;0<=U;U--)if(!K[U]){a=U;break}K=a%B*c.width;e.top=p+Math.floor(a/B)*c.height+(c.height-e.height);e.left=b+K+(c.width-
e.width);d.create(e)},a))};_.Z.prototype.wa=function(a,b){var c=this.a[b];c&&_.E(c)};_.Z.prototype.closePanel=_.Z.prototype.wa;_.Z.prototype.va=function(){for(var a in this.a)0==this.a[a].url.indexOf("panel.html")&&this.wa(0,a)};_.Z.prototype.closeAllPanels=_.Z.prototype.va;_.Z.prototype.setTitle=function(a,b,c){(a=this.a[b])&&a.setTitle(c)};_.Z.prototype.setTitle=_.Z.prototype.setTitle;_.Z.prototype.drawAttention=function(a,b,c){this.a[b]&&this.a[b].drawAttention(c)};
_.Z.prototype.drawAttention=_.Z.prototype.drawAttention;_.Z.prototype.focus=function(a){if(this.a[a]){var b=this.a[a];b.getProperties((0,_.r)(function(a){if(a&&(a=Sh(b),0==a.outerWidth&&0==a.outerHeight)){this.ra(b);return}b.focus()},this))}};_.Z.prototype.gc=function(a,b,c){this.a[b]&&$i(this.a[b],c)};_.Z.prototype.setPresence=_.Z.prototype.gc;_.Z.prototype.ec=function(a,b,c){this.a[b]&&aj(this.a[b],c)};_.Z.prototype.setAvatar=_.Z.prototype.ec;
_.Z.prototype.pa=function(a,b,c){for(var d in this.a)(b||this.b.contains(d))&&this.ab(0,d,b,c);b||this.b.clear()};_.Z.prototype.minimizeAllPanelsIfTopmost=_.Z.prototype.pa;
_.Z.prototype.ab=function(a,b,c,d){var e=this.a[b];e&&e.getProperties((0,_.r)(function(a){if(a&&a.alwaysOnTop&&!this.K)if(c){var g;(g=!d)||(g=new _.oh(a.left,a.top,a.width,a.height),g=g.left<=d.left+d.width&&d.left<=g.left+g.width&&g.top<=d.top+d.height&&d.top<=g.top+g.height);g&&!a.isMinimized()&&(e.minimize(),this.b.a[_.bj(b)]=null)}else window.chrome.windows.update(e.a,{state:"normal"}),this.b.remove(b)},this))};_.Z.prototype.minimizePanelIfTopmost=_.Z.prototype.ab;
_.Z.prototype.A=function(a){var b=this.a[a.location.search.substring(1)];b&&(b.f=a,Wi(b))};var Li=function(a,b,c){a=a.a[a.c[b]];!a||bi(a)?c(void 0):a.getProperties(c)},Gi=function(a,b,c){var d=[];(0,_.za)(b,(0,_.r)(function(a){d.push(this.a[this.c[a]])},a));Xi(d,c)};_.Z.prototype.ra=function(a){this.a[a.id]==a&&(this.b.remove(a.id),delete this.c[a.key],delete this.a[a.id],_.E(a))};_.Z.prototype.w=function(a){this.a[a.id]==a&&this.b.remove(a.id)}; _.Z.prototype.l=function(a){this.a[a.id]==a&&_.T.a().b("eventBlurred",[a.id])};_.Z.prototype.j=function(){3==this.h.a&&this.va()};

}catch(e){_._DumpException(e)}
try{
var fj=function(a,b){a.c.get(_.Ug).ta(0,b)},gj=function(a){var b=a.b.get("ReloadState");_.sa(b)&&"acq:rs"==b[0]&&(a.b.remove("ReloadState"),b=new _.xi(b),a.f=_.zd(b,_.ui,1),a.a={},_.yh(b,_.Ai,3)&&(0,_.za)(_.yh(b,_.Ai,3),function(a){var b=_.Fi(a.S(),a.ga());this.a[b]=a},a),_.zd(b,_.Mh,2)&&fj(a,b))},hj=function(a){var b=a.a;a.a=a.f;a.f=b;b=a.u;a.u=a.g;a.g=b},ij={a:/^https?:\/\/.*.google.com(:[0-9]+)?\/hangouts\/_\/.*/},jj=function(a){var b=[];null!=a&&(b=a.split("_;_"));if(2>b.length){a=2-b.length;
for(var c=0;c<a;++c)b.push("")}return b},kj=function(a){_.D.call(this);this.f=a;this.a=new _.cj;this.b=(0,_.r)(this.j,this);this.c=(0,_.r)(this.l,this);this.g=(0,_.r)(this.h,this);window.chrome.tabs.onCreated.addListener(this.b);window.chrome.tabs.onUpdated.addListener(this.c);window.chrome.tabs.onRemoved.addListener(this.g)};_.q(kj,_.D);
kj.prototype.v=function(){window.chrome.tabs.onCreated.removeListener(this.b);window.chrome.tabs.onUpdated.removeListener(this.c);window.chrome.tabs.onRemoved.removeListener(this.g);delete this.b;delete this.c;delete this.g;kj.B.v.call(this)};kj.prototype.j=function(a){a.url&&lj(this,a.id,a.windowId,a.url)};kj.prototype.l=function(a,b,c){b.url&&lj(this,a,c.windowId,b.url)};
kj.prototype.h=function(a){a=a.toString();if(this.a.contains(a)){this.a.remove(a);var b;a:{for(b in this.a.a){b=!1;break a}b=!0}b&&this.f.pa(0,!1)}};
var lj=function(a,b,c,d){b=b.toString();if(!a.a.contains(b))for(var e in ij)if(ij[e].test(d)){a.a.a[_.bj(b)]=null;window.chrome.windows.get(c,(0,_.r)(function(a){a&&!this.K&&this.f.pa(0,!0,new _.oh(a.left,a.top,a.width,a.height))},a));_.eh(c);break}},mj=function(){_.I.call(this);this.f=new _.H(this);_.F(this,this.f);this.a=new _.sh;_.F(this,this.a);this.h=(0,_.r)(this.j,this);this.g=(0,_.r)(this.b,this);window.chrome.idle.setDetectionInterval(300);this.b();window.chrome.idle.onStateChanged.addListener(this.g);
this.a.setInterval(2E4);this.f.listen(this.a,"tick",this.b);_.th(this.a)};_.q(mj,_.I);mj.prototype.v=function(){window.chrome.idle.onStateChanged.removeListener(this.g);mj.B.v.call(this)};mj.prototype.j=function(a){var b=_.T;switch(a){case "idle":case "locked":b.a().b("onIdleStateIdle",["i"]);break;case "active":b.a().b("onIdleStateActive",["a"])}};mj.prototype.b=function(){window.chrome.idle.queryState(300,this.h)};var nj=function(a,b){_.Db.call(this,a);this.message=b};_.q(nj,_.Db);
var oj=function(a){_.D.call(this);this.a=a;this.b=a.name;this.c=!0;this.j=null;_.n(a.sender)&&null!=a.sender.tab&&(this.j=a.sender.tab);this.f=null;this.g=(0,_.r)(this.pb,this);this.h=(0,_.r)(this.Ta,this)};_.q(oj,_.D);_.h=oj.prototype;_.h.v=function(){oj.B.v.call(this);this.Ta()};_.h.ca=function(){return jj(this.b)[1]};_.h.sendMessage=function(a){if(null==a||null==a.message||!this.a||!this.c)return!1;a=a.message();this.a.postMessage(a);return!0};
_.h.pb=function(a){var b=this.f;a=_.Pc(new _.J,a);if(null!=a&&null!=a.a)try{switch(a.g){case "e":var c=b.h.c(_.Xg);if(null!=c)a:try{var d;switch(a.h){case "dataChannelManager":d=_.Ug;break;case "desktopManager":d=_.Vg;break;case "extensionLibrary":d=_.Wg;break;case "notificationManager":d=_.Yg;break;case "panelsManager":d=_.Zg;break;case "settingsManager":d=_.$g;break;case "viewAreaManager":d=_.bh;break;default:break a}var e=a.c;if(null!=e){var f=c.a.get(d),g=[].concat(a.b),k=g.shift();if(_.t(f[k])){b=
{};b.source=a.a;b.sourceType=a.u;b.callbackId=e;g.unshift(b);var p=f[k].apply(f,g);if("delayedResponseCode"!=p){var B=_.T.b(a.a);hj(a);_.Sc(a,p);pj(B,a)}}}}catch(Sa){var K=_.T.b(a.a);if(null!=K&&K.c){var Ra=a.c;hj(a);_.Rc(a,"onError");_.Sc(a,[Ra,Sa]);K.sendMessage(a)}}break;case "p":case "c":switch(a.j){case "u":pj(b.b(a.f),a);break;case "m":var e=[],U=jj(a.f),R;for(R in b.f)U[0]==jj(b.b(R).b)[0]&&e.push(b.b(R));qj(e,a);break;case "b":for(var gb in b.f){var S=b.b(gb);null!=S&&S.c&&(_.wd(a,S.b),S.sendMessage(a))}break;
default:throw"Unknown RouteType.";}break;default:throw"Unknown TargetType.";}}catch(Sa){}};_.h.Ta=function(){if(this.a){var a=this.f,b=this.b;a.b(b)&&(delete a.f[b],a=a.a(),"viewer"==jj(b)[0]&&a.b("eventViewerClosed",[]))}this.a&&(this.a.onMessage.removeListener(this.g),this.a.onDisconnect.removeListener(this.h),delete this.a);delete this.g;delete this.h;delete this.j;delete this.f;delete this.c};
var rj=function(a){_.I.call(this);this.a=a;this.f=null;this.g=(0,_.r)(this.Mb,this);this.h=(0,_.r)(this.Rb,this);this.a.a(_.ah,_.Yc.ca());a=new _.Fh(this.a);this.a.a(_.$g,a);a=new _.X(this.a);this.a.a(_.Wg,a);a=new _.Y(this.a);this.a.a(_.Yg,a);this.f=new _.W(this.a);this.a.a(_.Vg,this.f);a=new _.Z(this.a);this.a.a(_.Zg,a);var b=new _.V(this.a);this.a.a(_.Ug,b);window.chrome.browserAction.onClicked.addListener((0,_.r)(this.fb,this));window.chrome.runtime.onMessageExternal.addListener((0,_.r)(this.Pb,
this));window.chrome.runtime.onConnectExternal.addListener((0,_.r)(this.Lb,this));window.chrome.hangoutsPrivate&&window.chrome.hangoutsPrivate.onHangoutRequested&&window.chrome.hangoutsPrivate.onHangoutRequested.addListener((0,_.r)(this.Ob,this));a.wa(0,"viewer");a=new kj(a);this.a.a(_.bh,a);this.j=new mj;_.F(this,this.j);this.a.a(_.Xg,this)};_.q(rj,_.I);rj.prototype.b=function(a,b){var c=JSON.stringify(sj(a,b).message());tj(_.T,"onSendHostMessage",sj("onSendHostMessage",c))};
var sj=function(a,b){var c=new _.J("p");_.Rc(c,a);_.Sc(c,b);_.Qc(c,"","e");return c};_.h=rj.prototype;_.h.Ob=function(a){var b=this.f.h()&&4==this.f.a&&(this.f.f||"")||"";!b||b!==a.from||1>a.to.length||tj(_.T,"onOpenConversation",sj("onOpenConversation",a.to[0].id))};_.h.fb=function(){var a=this.a.get(_.Ug);a.j||_.$h(a);this.ia()};_.h.Pb=function(a,b,c){"icjglmbkgdgdgdigllcokdabceikdppi"==b.id&&(this.fb(),c(a))};
_.h.Rb=function(a,b){var c=this.f.h()&&(this.f.f||"")||"";switch(a.eventType){case "getCentralJid":b.postMessage({jid:c});break;case "ocbek":case "ocfp":case "showChat":case "po":if(!c)break;this.b("eoc",[a.eventType,a.jid]);break;case "mmm":var c=this.a.get(_.bh),d=_.u(a.jid)?JSON.parse(a.jid):[];if(b.sender.tab){var e=b.sender.tab;if(d.length){var f;4==d.length&&(f=new _.oh(d[0],d[1],d[2],d[3]));c.a.a[_.bj(e.id.toString())]=null;c.f.pa(0,!0,f)}else c.h(e.id)}}};
_.h.Lb=function(a){a.onMessage.addListener(this.h);a.onDisconnect.addListener(this.g)};_.h.Mb=function(a){a.onMessage.removeListener(this.h);a.onDisconnect.removeListener(this.g)};_.h.Ba=function(){this.a.get(_.Ug).Ba();this.a.get(_.Vg).$(0,1)};_.h.ia=function(){this.a.get(_.Ug).ta()};_.h.Aa=function(){tj(_.T,"h_icr",sj("h_icr",[window.chrome.runtime.id]));this.b("eventExtensionInfo",[window.chrome.runtime.id,{reinstall:!0}])};var uj=function(a){_.I.call(this);this.h=a;this.f={}};_.q(uj,_.I);
uj.prototype.a=function(){return this.h.get(_.Xg)};var vj=function(){window.chrome.runtime.onConnect.addListener(function(a){var b=_.T,c=a.name;a=new oj(a);a.f=b;a.a.onMessage.addListener(a.g);a.a.onDisconnect.addListener(a.h);b.f[""+c]=a});window.chrome.runtime.onMessage.addListener(function(a){var b=_.T;a=_.Pc(new _.J,a);if(null!=a)switch(b=b.a(),a.c){case "changeDesktop":b.f.$(0,a.b[0])}})};uj.prototype.b=function(a){return null!=a?this.f[a]:null};
uj.prototype.g=function(a){var b=[],c;for(c in this.f)jj(this.b(c).b)[0]==a&&b.push(c);return b};var pj=function(a,b){null!=a&&a.c&&(_.wd(b,a.b),a.sendMessage(b))},qj=function(a,b){for(var c=0;c<a.length;c++){var d=a[c];null!=d&&d.c&&(_.wd(b,d.b),d.sendMessage(b))}};uj.prototype.j=function(){_.M(this,new nj("onStatusChange",new _.J))};
var tj=function(a,b,c){var d=_.T.g("quasar");if(null!=b&&null!=c&&null!=d&&!(1>d.length)){c.j="u";_.Rc(c,b);b=[];for(var e=0;e<d.length;e++)a.b(d[e])&&b.push(a.b(d[e]));qj(b,c)}},wj,xj=function(){var a=new _.md;wj=a;var b=new uj(a);null==_.T&&null!=b&&(_.T=b);b=new rj(a);vj();var c=!1,d=a.get(_.ah);d.has("has_installed")||(d.set("has_installed",!0),c=!0);if((a=a.get(_.$g).a.a.get("StartOnBrowserLaunch"))&&a.W&&a.F()||d.has("ReloadState"))a=c,c=b.a.get(_.Ug),_.$h(c),a?c.ta():gj(b.a.get(_.Wg).a)}; window.addEventListener("load",function(){_.Yc.ca().T(xj)},!1);window.addEventListener("beforeunload",function(){_.T.a().a.get(_.Yg).na();_.E(wj);wj=void 0},!1);

}catch(e){_._DumpException(e)}
}).call(this,this.default_main);
// Google Inc.
