"use strict";this.default_settings=this.default_settings||{};(function(_){var window=this;
try{
var aa,ba,ca,da;for(_.h,aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},ba="undefined"!=typeof window&&window===this?this:"undefined"!=typeof window.global?window.global:this,ca=["String","prototype","repeat"],da=0;da<ca.length-1;da++){var ea=ca[da];ea in ba||(ba[ea]={});ba=ba[ea]}
var fa=ca[ca.length-1],ga=ba[fa],ha=ga?ga:function(a){var b;if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");b=this+"";if(0>a||1342177279<a)throw new window.RangeError("Invalid count value");a|=0;for(var c="";a;)if(a&1&&(c+=b),a>>>=1)b+=b;return c};ha!=ga&&null!=ha&&aa(ba,fa,{configurable:!0,writable:!0,value:ha});_.ia=_.ia||{};_.l=this;_.ja="closure_uid_"+(1E9*Math.random()>>>0);_.m=Date.now||function(){return+new Date};

}catch(e){_._DumpException(e)}
try{
var ka,la,ma;_.n=function(a){return void 0!==a};ka=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};la=function(a,b,c){return a.call.apply(a.bind,arguments)};
ma=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.q=function(a,b){function c(){}c.prototype=b.prototype;a.B=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.nc=function(a,c,f){for(var g=Array(arguments.length-2),k=2;k<arguments.length;k++)g[k-2]=arguments[k];return b.prototype[c].apply(a,g)}};
_.na=function(a,b){var c=a.split("."),d=_.l;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&_.n(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}};_.oa=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.r=function(a,b,c){_.r=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?la:ka;return _.r.apply(null,arguments)};
_.pa=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.t=function(a){return"function"==ma(a)};_.qa=function(a){return"number"==typeof a};_.u=function(a){return"string"==typeof a};_.ra=function(a){var b=ma(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.sa=function(a){return"array"==ma(a)};_.ta=function(){};_.ua=function(a,b){for(var c=a.split("."),d=b||_.l,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d}; _.va=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.va);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};_.q(_.va,Error);_.va.prototype.name="CustomError";
var wa=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},xa=function(a,b){return a<b?-1:a>b?1:0};_.ya=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.u(a))return _.u(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};_.za=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.u(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.Aa=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=_.u(a)?a.split(""):a,k=0;k<d;k++)if(k in g){var p=g[k];b.call(c,p,k,a)&&(e[f++]=p)}return e};_.Ba=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=_.u(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};
_.Ca=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.u(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.Da=function(a,b){var c=(0,_.ya)(a,b),d;(d=0<=c)&&Array.prototype.splice.call(a,c,1);return d};
a:{var Fa=_.l.navigator;if(Fa){var Ga=Fa.userAgent;if(Ga){_.Ea=Ga;break a}}_.Ea=""}_.v=function(a){return-1!=_.Ea.indexOf(a)};var Ia;_.Ha=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};Ia=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};_.Ja=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};var Ka=function(){return(_.v("Chrome")||_.v("CriOS"))&&!_.v("Edge")};_.La=function(){return _.v("iPhone")&&!_.v("iPod")&&!_.v("iPad")};var Ma=function(a){Ma[" "](a);return a},Pa;Ma[" "]=_.ta;_.Na=function(a,b){try{return Ma(a[b]),!0}catch(c){}return!1};Pa=function(a,b){var c=Oa;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var Wa,Ya,Za,Oa,eb,fb;_.Qa=_.v("Opera");_.w=_.v("Trident")||_.v("MSIE");_.Ta=_.v("Edge");_.Ua=_.v("Gecko")&&!(-1!=_.Ea.toLowerCase().indexOf("webkit")&&!_.v("Edge"))&&!(_.v("Trident")||_.v("MSIE"))&&!_.v("Edge");_.Va=-1!=_.Ea.toLowerCase().indexOf("webkit")&&!_.v("Edge");Wa=_.l.navigator||null;_.Xa=Wa&&Wa.platform||"";Ya=function(){var a=_.l.document;return a?a.documentMode:void 0};
a:{var $a="",ab=function(){var a=_.Ea;if(_.Ua)return/rv\:([^\);]+)(\)|;)/.exec(a);if(_.Ta)return/Edge\/([\d\.]+)/.exec(a);if(_.w)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.Va)return/WebKit\/(\S+)/.exec(a);if(_.Qa)return/(?:Version)[ \/]?(\S+)/.exec(a)}();ab&&($a=ab?ab[1]:"");if(_.w){var bb=Ya();if(null!=bb&&bb>(0,window.parseFloat)($a)){Za=String(bb);break a}}Za=$a}_.cb=Za;Oa={};
_.db=function(a){return Pa(a,function(){for(var b=0,c=wa(String(_.cb)).split("."),d=wa(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",k=d[f]||"";do{g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];if(0==g[0].length&&0==k[0].length)break;b=xa(0==g[1].length?0:(0,window.parseInt)(g[1],10),0==k[1].length?0:(0,window.parseInt)(k[1],10))||xa(0==g[2].length,0==k[2].length)||xa(g[2],k[2]);g=g[3];k=k[3]}while(0==b)}return 0<=b})}; eb=_.l.document;fb=eb&&_.w?Ya()||("CSS1Compat"==eb.compatMode?(0,window.parseInt)(_.cb,10):5):void 0;
_.hb=_.v("Firefox");_.ib=_.La()||_.v("iPod");_.jb=_.v("iPad");_.kb=_.v("Android")&&!(Ka()||_.v("Firefox")||_.v("Opera")||_.v("Silk"));_.lb=Ka();_.mb=_.v("Safari")&&!(Ka()||_.v("Coast")||_.v("Opera")||_.v("Edge")||_.v("Silk")||_.v("Android"))&&!(_.La()||_.v("iPad")||_.v("iPod"));
_.nb=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;var ob,rb,sb;_.x=function(){};ob="function"==typeof window.Uint8Array;_.y=function(a,b,c,d){a.a=null;b||(b=c?[c]:[]);a.D=c?String(c):void 0;a.f=0===c?-1:0;a.b=b;a:{if(a.b.length&&(b=a.b.length-1,(c=a.b[b])&&"object"==typeof c&&!_.sa(c)&&!(ob&&c instanceof window.Uint8Array))){a.u=b-a.f;a.c=c;break a}a.u=Number.MAX_VALUE}a.C={};if(d)for(b=0;b<d.length;b++)c=d[b],c<a.u?(c+=a.f,a.b[c]=a.b[c]||_.pb):a.c[c]=a.c[c]||_.pb};_.pb=[];
_.z=function(a,b){if(b<a.u){var c=b+a.f,d=a.b[c];return d===_.pb?a.b[c]=[]:d}d=a.c[b];return d===_.pb?a.c[b]=[]:d};rb=function(a){if(a.a)for(var b in a.a){var c=a.a[b];if(_.sa(c))for(var d=0;d<c.length;d++)c[d]&&_.qb(c[d]);else c&&_.qb(c)}};_.qb=function(a){rb(a);return a.b};_.x.prototype.toString=function(){rb(this);return this.b.toString()};_.A=function(a,b){sb[a]=b;b.messageId=a};sb={};
_.tb=function(a){return function(){return a}}(!0);_.ub="StopIteration"in _.l?_.l.StopIteration:{message:"StopIteration",stack:""};_.vb=function(){};_.vb.prototype.next=function(){throw _.ub;};_.vb.prototype.Y=function(){return this};_.C=function(a,b){this.b={};this.a=[];this.f=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("e");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof _.C?(c=a.M(),d=a.G()):(c=_.Ja(a),d=Ia(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};_.h=_.C.prototype;_.h.ba=function(){return this.c};_.h.G=function(){wb(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};_.h.M=function(){wb(this);return this.a.concat()};
_.h.clear=function(){this.b={};this.f=this.c=this.a.length=0};_.h.remove=function(a){return _.xb(this.b,a)?(delete this.b[a],this.c--,this.f++,this.a.length>2*this.c&&wb(this),!0):!1};var wb=function(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];_.xb(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],_.xb(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};_.C.prototype.get=function(a,b){return _.xb(this.b,a)?this.b[a]:b};
_.C.prototype.set=function(a,b){_.xb(this.b,a)||(this.c++,this.a.push(a),this.f++);this.b[a]=b};_.C.prototype.forEach=function(a,b){for(var c=this.M(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};_.C.prototype.Y=function(a){wb(this);var b=0,c=this.f,d=this,e=new _.vb;e.next=function(){if(c!=d.f)throw Error("f");if(b>=d.a.length)throw _.ub;var e=d.a[b++];return a?e:d.b[e]};return e};_.xb=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
_.yb=function(a){if(a.G&&"function"==typeof a.G)return a.G();if(_.u(a))return a.split("");if(_.ra(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Ia(a)};_.D=function(){this.K=this.K;this.u=this.u};_.D.prototype.K=!1;_.D.prototype.N=function(){this.K||(this.K=!0,this.v())};_.F=function(a,b){_.zb(a,_.oa(_.E,b))};_.zb=function(a,b){a.K?_.n(void 0)?b.call(void 0):b():(a.u||(a.u=[]),a.u.push(_.n(void 0)?(0,_.r)(b,void 0):b))};_.D.prototype.v=function(){if(this.u)for(;this.u.length;)this.u.shift()()};_.E=function(a){a&&"function"==typeof a.N&&a.N()};
_.Ab=!_.w||9<=Number(fb);!_.Ua&&!_.w||_.w&&9<=Number(fb)||_.Ua&&_.db("1.9.1");_.w&&_.db("9");var Bb=!_.w||9<=Number(fb),Cb=_.w&&!_.db("9");!_.Va||_.db("528");_.Ua&&_.db("1.9b")||_.w&&_.db("8")||_.Qa&&_.db("9.5")||_.Va&&_.db("528");_.Ua&&!_.db("8")||_.w&&_.db("9");_.Db=function(a,b){this.type=a;this.a=this.b=b;this.eb=!0};_.Db.prototype.c=function(){this.eb=!1};var Eb=function(a,b){_.Db.call(this,a?a.type:"");this.f=this.state=this.a=this.b=null;a&&this.T(a,b)};_.q(Eb,_.Db);Eb.prototype.T=function(a,b){this.type=a.type;this.b=a.target||a.srcElement;this.a=b;var c=a.relatedTarget;c&&_.Ua&&_.Na(c,"nodeName");this.state=a.state;this.f=a;a.defaultPrevented&&this.c()};Eb.prototype.c=function(){Eb.B.c.call(this);var a=this.f;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Cb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var Fb,Hb;Fb="closure_listenable_"+(1E6*Math.random()|0);_.Gb=function(a){return!(!a||!a[Fb])};Hb=0;var Ib=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.ma=!!d;this.oa=e;this.key=++Hb;this.removed=this.la=!1},Jb=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.oa=null};var Kb;Kb=function(a){this.src=a;this.a={};this.b=0};_.Mb=function(a,b,c,d,e,f){var g=b.toString();b=a.a[g];b||(b=a.a[g]=[],a.b++);var k=Lb(b,c,e,f);-1<k?(a=b[k],d||(a.la=!1)):(a=new Ib(c,a.src,g,!!e,f),a.la=d,b.push(a));return a};Kb.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Lb(e,b,c,d);return-1<b?(Jb(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var Nb=function(a,b){var c=b.type;c in a.a&&_.Da(a.a[c],b)&&(Jb(b),0==a.a[c].length&&(delete a.a[c],a.b--))};Kb.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,Jb(d[e]);delete this.a[c];this.b--}return b};var Ob=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=Lb(a,c,d,e));return-1<b?a[b]:null},Lb=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.ma==!!c&&f.oa==d)return e}return-1};
var Pb,Qb,Rb,Wb,Zb,$b,Xb,bc,ac,Yb,Vb,cc;Pb="closure_lm_"+(1E6*Math.random()|0);Qb={};Rb=0;_.Sb=function(a,b,c,d,e){if(_.sa(b)){for(var f=0;f<b.length;f++)_.Sb(a,b[f],c,d,e);return null}c=_.Tb(c);return _.Gb(a)?a.listen(b,c,d,e):_.Ub(a,b,c,!1,d,e)};
_.Ub=function(a,b,c,d,e,f){if(!b)throw Error("i");var g=!!e,k=Vb(a);k||(a[Pb]=k=new Kb(a));c=_.Mb(k,b,c,d,e,f);if(c.proxy)return c;d=Wb();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,g);else if(a.attachEvent)a.attachEvent(Xb(b.toString()),d);else throw Error("j");Rb++;return c};Wb=function(){var a=Yb,b=Bb?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b};
Zb=function(a,b,c,d,e){if(_.sa(b))for(var f=0;f<b.length;f++)Zb(a,b[f],c,d,e);else c=_.Tb(c),_.Gb(a)?a.Ca(b,c,d,e):a&&(a=Vb(a))&&(b=Ob(a,b,c,!!d,e))&&$b(b)};$b=function(a){if(_.qa(a)||!a||a.removed)return;var b=a.src;if(_.Gb(b)){Nb(b.c,a);return}var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.ma):b.detachEvent&&b.detachEvent(Xb(c),d);Rb--;(c=Vb(b))?(Nb(c,a),0==c.b&&(c.src=null,b[Pb]=null)):Jb(a)};Xb=function(a){return a in Qb?Qb[a]:Qb[a]="on"+a};
bc=function(a,b,c,d){var e=!0;if(a=Vb(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.ma==c&&!f.removed&&(f=ac(f,d),e=e&&!1!==f)}return e};ac=function(a,b){var c=a.listener,d=a.oa||a.src;a.la&&$b(a);return c.call(d,b)};
Yb=function(a,b){if(a.removed)return!0;if(!Bb){var c=b||_.ua("window.event"),d=new Eb(c,this),e=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var f=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(p){f=!0}if(f||void 0==c.returnValue)c.returnValue=!0}c=[];for(f=d.a;f;f=f.parentNode)c.push(f);for(var f=a.type,g=c.length-1;0<=g;g--){d.a=c[g];var k=bc(c[g],f,!0,d),e=e&&k}for(g=0;g<c.length;g++)d.a=c[g],k=bc(c[g],f,!1,d),e=e&&k}return e}return ac(a,new Eb(b,this))}; Vb=function(a){a=a[Pb];return a instanceof Kb?a:null};cc="__closure_events_fn_"+(1E9*Math.random()>>>0);_.Tb=function(a){if(_.t(a))return a;a[cc]||(a[cc]=function(b){return a.handleEvent(b)});return a[cc]};
_.dc=function(a){_.y(this,a,"h_cc",null)};_.q(_.dc,_.x);_.A("h_cc",_.dc);_.dc.prototype.S=function(){return _.z(this,19)};_.G=function(a){this.a=a};_.G.prototype.toString=function(){return this.a};_.H=function(a){_.D.call(this);this.I=a;this.f={}};_.q(_.H,_.D);var ec=[];_.H.prototype.listen=function(a,b,c,d){return _.fc(this,a,b,c,d)};_.fc=function(a,b,c,d,e,f){_.sa(c)||(c&&(ec[0]=c.toString()),c=ec);for(var g=0;g<c.length;g++){var k=_.Sb(b,c[g],d||a.handleEvent,e||!1,f||a.I||a);if(!k)break;a.f[k.key]=k}return a};
_.H.prototype.Ca=function(a,b,c,d,e){if(_.sa(b))for(var f=0;f<b.length;f++)this.Ca(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.I||this,c=_.Tb(c),d=!!d,b=_.Gb(a)?Ob(a.c,String(b),c,d,e):a?(a=Vb(a))?Ob(a,b,c,d,e):null:null,b&&($b(b),delete this.f[b.key]);return this};_.H.prototype.removeAll=function(){_.Ha(this.f,function(a,b){this.f.hasOwnProperty(b)&&$b(a)},this);this.f={}};_.H.prototype.v=function(){_.H.B.v.call(this);this.removeAll()}; _.H.prototype.handleEvent=function(){throw Error("m");};
var gc=function(a,b,c){this.f=c;this.c=a;this.u=b;this.b=0;this.a=null};gc.prototype.get=function(){var a;0<this.b?(this.b--,a=this.a,this.a=a.next,a.next=null):a=this.c();return a};var hc=function(a,b){a.u(b);a.b<a.f&&(a.b++,b.next=a.a,a.a=b)};var ic,jc,kc;ic=function(a){_.l.setTimeout(function(){throw a;},0)};_.lc=function(a,b){var c=a;b&&(c=(0,_.r)(a,b));!_.t(_.l.setImmediate)||_.l.Window&&_.l.Window.prototype&&!_.v("Edge")&&_.l.Window.prototype.setImmediate==_.l.setImmediate?(jc||(jc=kc()),jc(c)):_.l.setImmediate(c)};
kc=function(){var a=_.l.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!_.v("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,_.r)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!_.v("Trident")&&!_.v("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.n(c.next)){c=c.next;var a=c.Va;c.Va=null;a()}};return function(a){d.next={Va:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b= window.document.createElement("SCRIPT");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){_.l.setTimeout(a,0)}};
var mc=function(){this.b=this.a=null},oc=new gc(function(){return new nc},function(a){a.reset()},100);mc.prototype.remove=function(){var a=null;this.a&&(a=this.a,this.a=this.a.next,this.a||(this.b=null),a.next=null);return a};var nc=function(){this.next=this.b=this.a=null};nc.prototype.set=function(a,b){this.a=a;this.b=b;this.next=null};nc.prototype.reset=function(){this.next=this.b=this.a=null};
var tc=function(a,b){pc||qc();rc||(pc(),rc=!0);var c=sc,d=oc.get();d.set(a,b);c.b?c.b.next=d:c.a=d;c.b=d},pc,qc=function(){if(_.l.Promise&&_.l.Promise.resolve){var a=_.l.Promise.resolve(void 0);pc=function(){a.then(uc)}}else pc=function(){_.lc(uc)}},rc=!1,sc=new mc,uc=function(){for(var a;a=sc.remove();){try{a.a.call(a.b)}catch(b){ic(b)}hc(oc,a)}rc=!1};
_.I=function(){_.D.call(this);this.c=new Kb(this);this.O=this;this.D=null};_.q(_.I,_.D);_.I.prototype[Fb]=!0;_.h=_.I.prototype;_.h.removeEventListener=function(a,b,c,d){Zb(this,a,b,c,d)};_.h.v=function(){_.I.B.v.call(this);this.c&&this.c.removeAll(void 0);this.D=null};_.h.listen=function(a,b,c,d){return _.Mb(this.c,String(a),b,!1,c,d)};_.h.Ca=function(a,b,c,d){return this.c.remove(String(a),b,c,d)}; _.h.X=function(a,b,c){a=this.c.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.ma==b){var g=f.listener,k=f.oa||f.src;f.la&&Nb(this.c,f);d=!1!==g.call(k,c)&&d}}return d&&0!=c.eb};
var vc=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},wc=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var yc=function(a,b){this.a=0;this.h=void 0;this.c=this.b=this.f=null;this.u=this.g=!1;if(a!=_.ta)try{var c=this;a.call(b,function(a){xc(c,2,a)},function(a){xc(c,3,a)})}catch(d){xc(this,3,d)}},zc=function(){this.next=this.c=this.b=this.f=this.a=null;this.u=!1},Ac,Bc;zc.prototype.reset=function(){this.c=this.b=this.f=this.a=null;this.u=!1};Ac=new gc(function(){return new zc},function(a){a.reset()},100);Bc=function(a,b,c){var d=Ac.get();d.f=a;d.b=b;d.c=c;return d};
_.Dc=function(){var a,b=new yc(function(b){a=b});return new Cc(b,a)};yc.prototype.then=function(a,b,c){return Ec(this,_.t(a)?a:null,_.t(b)?b:null,c)};vc(yc);
var Gc=function(a,b){a.b||2!=a.a&&3!=a.a||Fc(a);a.c?a.c.next=b:a.b=b;a.c=b},Ec=function(a,b,c,d){var e=Bc(null,null,null);e.a=new yc(function(a,g){e.f=b?function(c){try{var e=b.call(d,c);a(e)}catch(B){g(B)}}:a;e.b=c?function(b){try{var e=c.call(d,b);!_.n(e)&&"undefined"!=typeof Hc&&b instanceof Hc?g(b):a(e)}catch(B){g(B)}}:g});e.a.f=a;Gc(a,e);return e.a};yc.prototype.l=function(a){this.a=0;xc(this,2,a)};yc.prototype.w=function(a){this.a=0;xc(this,3,a)};
var xc=function(a,b,c){if(0==a.a){a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.a=1;var d;a:{var e=c,f=a.l,g=a.w;if(e instanceof yc)Gc(e,Bc(f||_.ta,g||null,a)),d=!0;else if(wc(e))e.then(f,g,a),d=!0;else{if(_.pa(e))try{var k=e.then;if(_.t(k)){Ic(e,k,f,g,a);d=!0;break a}}catch(p){g.call(a,p);d=!0;break a}d=!1}}d||(a.h=c,a.a=b,a.f=null,Fc(a),3!=b||"undefined"!=typeof Hc&&c instanceof Hc||Jc(a,c))}},Ic=function(a,b,c,d,e){var f=!1,g=function(a){f||(f=!0,c.call(e,a))},k=function(a){f||
(f=!0,d.call(e,a))};try{b.call(a,g,k)}catch(p){k(p)}},Fc=function(a){a.g||(a.g=!0,tc(a.j,a))},Kc=function(a){var b=null;a.b&&(b=a.b,a.b=b.next,b.next=null);a.b||(a.c=null);return b};yc.prototype.j=function(){for(var a;a=Kc(this);){var b=this.a,c=this.h;if(3==b&&a.b&&!a.u){var d;for(d=this;d&&d.u;d=d.f)d.u=!1}if(a.a)a.a.f=null,Lc(a,b,c);else try{a.u?a.f.call(a.c):Lc(a,b,c)}catch(e){Mc.call(null,e)}hc(Ac,a)}this.g=!1}; var Lc=function(a,b,c){2==b?a.f.call(a.c,c):a.b&&a.b.call(a.c,c)},Jc=function(a,b){a.u=!0;tc(function(){a.u&&Mc.call(null,b)})},Mc=ic,Hc=function(a){_.va.call(this,a)};_.q(Hc,_.va);Hc.prototype.name="cancel";var Cc=function(a,b){this.b=a;this.a=b};
_.Nc=function(a,b){for(var c=[],d=0;d<arguments.length;d++)c.push(arguments[d]||"");return c.join("_;_")};_.Oc=function(){return 0<=window.navigator.userAgent.indexOf("CrOS")};_.J=function(a,b){this.g=a||"e";this.u=null!=a&&"p"==a?"e":"p";this.a=this.f=null;this.j=b||"u";this.c=this.h=null;this.b=[]};_.J.prototype.message=function(){var a={};a.i=this.c;a.m=this.b;a.r=this.j;a.o=this.h;a.s=this.a;a.st=this.u;a.d=this.f;a.dt=this.g;return a};_.J.prototype.message=_.J.prototype.message;
_.Pc=function(a,b){for(var c in b)switch(c){case "r":a.j=b[c];break;case "i":a.c=b[c];break;case "m":a.b=b[c];break;case "o":a.h=b[c];break;case "s":a.a=b[c];break;case "d":a.f=b[c];break;case "st":a.u=b[c];break;case "dt":a.g=b[c]}return a};_.Qc=function(a,b,c){null!=b&&(a.a=b,null!=c&&(a.u=c))};_.Rc=function(a,b){null!=b&&(a.c=b)};_.Sc=function(a,b){"object"==typeof b?a.b=b:a.b=[b]};
_.Tc=function(a,b,c,d,e){_.D.call(this);this.b=a;this.ja=b;this.a=typeof b;this.za=c?c:!1;this.W=!0;this.ya=d?d:!1;this.ua=e?e:!1};_.q(_.Tc,_.D);_.h=_.Tc.prototype;_.h.v=function(){_.Tc.B.v.call(this);this.b="";this.ja=null;this.a=""};_.h.id=function(){return this.b};_.h.type=function(){return this.a};_.h.F=function(){return this.ja};_.h.setEnabled=function(a){this.W=a};
_.Vc=function(a){_.D.call(this);this.a=new _.C;this.b=["https://hangouts.google.com","","https://autopush.hangouts.sandbox.google.com?jsmode=du"];a&&_.Uc(this,a)};_.q(_.Vc,_.D);_.Wc=!_.Oc();_.Vc.prototype.v=function(){_.Vc.B.v.call(this);for(var a=this.a.M(),b=0;b<a.length;++b)_.E(this.a.get(a[b]));delete this.a};_.Vc.prototype.getItem=function(a){return _.xb(this.a.b,a)?this.a.get(a):null};_.Vc.prototype.setItem=function(a){this.a.set(a.id(),a)}; _.Uc=function(a,b){for(var c in b){var d=b[c],e;_.xb(a.a.b,c)?(e=a.a.get(c),e.ja=d.value,d.changed&&(e.ua=d.changed)):(e=new _.Tc(c,d.value,d.multiple,d.inverse,d.changed),e.setEnabled(!d.disabled));a.a.set(c,e)}};
_.Yc=function(){this.b=new _.C;this.a=null;this.c=!1;window.chrome.storage||(this.a=new Xc,this.c=!0);this.T()};_.Yc.ca=function(){return _.Yc.a?_.Yc.a:_.Yc.a=new _.Yc};_.h=_.Yc.prototype;_.h.T=function(a){var b=a||_.ta;this.c?b():window.chrome.storage.local.get((0,_.r)(function(a){if(!this.c){for(var d in a)this.b.set(d,a[d]);this.c=!0}b()},this))};_.h.get=function(a){return window.chrome.storage?this.b.get(a,null):this.a.get(a)};
_.h.has=function(a){return window.chrome.storage?_.xb(this.b.b,a):this.a.has(a)};_.h.set=function(a,b){var c=_.Dc();if(window.chrome.storage){this.b.set(a,b);var d={};d[a]=b;window.chrome.storage.local.set(d,function(){c.a(void 0)})}else this.a.set(a,b),c.a(void 0);return c.b};_.h.remove=function(a){window.chrome.storage?(this.b.remove(a),window.chrome.storage.local.remove(a,function(){})):this.a.remove(a)};
_.h.clear=function(){window.chrome.storage?(this.b.clear(),window.chrome.storage.local.clear(function(){})):this.a.clear()};var Xc=function(){this.a=window.localStorage};_.h=Xc.prototype;_.h.clear=function(){this.a.clear()};_.h.get=function(a){a=this.a.getItem(a);if(a){var b=JSON.parse(a);a=b.data;if("jspb"==b.type){b=sb[a[0]];if(!b)throw Error("c`"+a[0]);a=new b(a)}}else a=null;return a};_.h.has=function(a){return null!=this.get(a)}; _.h.set=function(a,b){var c=null;b instanceof _.x&&(b=_.qb(b),c="jspb");var d={};d.data=b;d.timestamp=(0,_.m)();c&&(d.type=c);c=JSON.stringify(d);try{this.a.setItem(a,c)}catch(e){}};_.h.remove=function(a){try{this.a.removeItem(a)}catch(b){}};
/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
var Zc=function(a,b){this.f=[];this.D=b||null;this.a=this.b=!1;this.c=void 0;this.l=this.w=this.g=!1;this.u=0;this.h=null;this.A=0};Zc.prototype.j=function(a,b){this.g=!1;this.b=!0;this.c=b;this.a=!a;$c(this)};Zc.prototype.C=function(a){if(this.b){if(!this.l)throw new ad;this.l=!1}this.b=!0;this.c=a;this.a=!1;$c(this)};var bd=function(a,b,c){a.f.push([b,c,void 0]);a.b&&$c(a)};
Zc.prototype.then=function(a,b,c){var d,e,f=new yc(function(a,b){d=a;e=b});bd(this,d,function(a){e(a)});return f.then(a,b,c)};vc(Zc);
var cd=function(a){return(0,_.Ca)(a.f,function(a){return _.t(a[1])})},$c=function(a){if(a.u&&a.b&&cd(a)){var b=a.u,c=dd[b];c&&(_.l.clearTimeout(c.a),delete dd[b]);a.u=0}a.h&&(a.h.A--,delete a.h);for(var b=a.c,d=c=!1;a.f.length&&!a.g;){var e=a.f.shift(),f=e[0],g=e[1],e=e[2];if(f=a.a?g:f)try{var k=f.call(e||a.D,b);_.n(k)&&(a.a=a.a&&(k==b||k instanceof Error),a.c=b=k);if(wc(b)||"function"===typeof _.l.Promise&&b instanceof _.l.Promise)d=!0,a.g=!0}catch(p){b=p,a.a=!0,cd(a)||(c=!0)}}a.c=b;d&&(k=(0,_.r)(a.j,
a,!0),d=(0,_.r)(a.j,a,!1),b instanceof Zc?(bd(b,k,d),b.w=!0):b.then(k,d));c&&(b=new ed(b),dd[b.a]=b,a.u=b.a)},ad=function(){_.va.call(this)};_.q(ad,_.va);ad.prototype.message="Deferred has already fired";ad.prototype.name="AlreadyCalledError";var ed=function(a){this.a=_.l.setTimeout((0,_.r)(this.c,this),0);this.b=a};ed.prototype.c=function(){delete dd[this.a];throw this.b;};var dd={};

}catch(e){_._DumpException(e)}
try{
var hd;_.fd=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);else if(_.ra(a)||_.u(a))(0,_.za)(a,b,void 0);else{var c;if(a.M&&"function"==typeof a.M)c=a.M();else if(a.G&&"function"==typeof a.G)c=void 0;else if(_.ra(a)||_.u(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=_.Ja(a);for(var d=_.yb(a),e=d.length,f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}};_.gd=function(a){a&&a.parentNode&&a.parentNode.removeChild(a)}; hd=function(a,b){for(var c=_.u(a)?a.split(""):a,d=a.length-1;0<=d;--d)d in c&&b.call(void 0,c[d],d,a)};
var id=function(a,b){this.c=a;this.b=b;this.constructor.Ua||(this.constructor.Ua={});this.constructor.Ua[this.toString()]=this};id.prototype.toString=function(){this.a||(this.a=this.c.a+":"+this.b);return this.a};var jd=function(a,b){id.call(this,a,b)};_.q(jd,id);var kd=function(a){this.a=a};new kd("lib");_.md=function(a){_.D.call(this);this.b={};this.l={};this.w={};this.f={};this.A={};this.D={};this.C=a?a.g():new _.I;this.J=!a;this.h=null;a?(this.h=a,this.w=a.w,this.f=a.f,this.l=a.l,this.A=a.A):(0,_.m)();a=ld(this);this!=a&&(a.j?a.j.push(this):a.j=[this])};_.q(_.md,_.D);var ld=function(a){for(;a.h;)a=a.h;return a};_.md.prototype.get=function(a){var b=this.c(a);if(null==b)throw new nd(a);return b};
_.md.prototype.c=function(a){for(var b=this;b;b=b.h){if(b.K)throw Error("o");if(b.b[a])return b.b[a][0];if(b.D[a])break}if(b=this.w[a]){b=b(this);if(null==b)throw Error("p`"+a);this.a(a,b);return b}return null};_.md.prototype.a=function(a,b,c){if(this.K)c||_.E(b);else{this.b[a]=[b,!c];b=od(this,this,a);for(c=0;c<b.length;c++)b[c].C(null);delete this.l[a]}};_.md.prototype.I=function(){var a=_.pd;if(!this.b[a])throw Error("q`"+a);var b=this.b[a];delete this.b[a];b[1]&&_.E(b[0])};
var od=function(a,b,c){var d=[],e=a.f[c];e&&(hd(e,function(a){var c;a:{for(c=a.qb;c;){if(c==b){c=!0;break a}c=c.h}c=!1}c&&(d.push(a.d),_.Da(e,a))}),0==e.length&&delete a.f[c]);return d},qd=function(a,b){a.f&&_.fd(a.f,function(a,d,e){hd(a,function(d){d.qb==b&&_.Da(a,d)});0==a.length&&delete e[d]})};
_.md.prototype.v=function(){if(ld(this)==this){var a=this.j;if(a)for(;a.length;)a[0].N()}else for(var a=ld(this).j,b=0;b<a.length;b++)if(a[b]==this){a.splice(b,1);break}for(var c in this.b)a=this.b[c],a[1]&&a[0].N&&a[0].N();this.b=null;this.J&&this.C.N();qd(this,this);this.f=null;_.E(this.H);this.D=this.H=null;_.md.B.v.call(this)};_.md.prototype.g=function(){return this.C};var nd=function(a){_.va.call(this);this.id=a;this.message='Service for "'+a+'" is not registered'};_.q(nd,_.va);var rd=new kd("fva"); new jd(rd,1);

}catch(e){_._DumpException(e)}
try{
_.ce=function(){return window.chrome.runtime.getURL("feedbackdialog.html")};
}catch(e){_._DumpException(e)}
try{
_.Sg=function(a){for(var b=a.a.M(),c={},d=0;d<b.length;d++){var e=b[d],f=a.a.get(e);c[e]={value:f.F(),type:f.type(),multiple:f.za,disabled:!f.W,inverse:f.ya,changed:f.ua}}return c};_.Tg=function(a,b){return _.u(b)?a.getElementById(b):b};_.Q=function(a){return _.Tg(window.document,a)};_.Ug=new _.G("a");_.Vg=new _.G("b");_.Wg=new _.G("c");_.Xg=new _.G("d");_.Yg=new _.G("e");_.Zg=new _.G("f");_.$g=new _.G("g");_.ah=new _.G("h");_.pd=new _.G("i");_.bh=new _.G("j");

}catch(e){_._DumpException(e)}
try{
var Bj=function(a,b){for(var c=a.split("%s"),d="",e=Array.prototype.slice.call(arguments,1);e.length&&1<c.length;)d+=c.shift()+e.shift();return d+c.join("%s")},Cj=function(a){_.D.call(this);this.f=_.Nc("setting",""+(0,_.m)());this.c=null;this.b=new _.H;_.F(this,this.b);this.a=new _.C;this.g=a.get(_.ah);this.b.listen(window,"unload",this.N)};_.q(Cj,_.D);_.na("ace.ui.SettingsDialog",Cj);_.na("ace.ui.SettingsDialog",Cj);
Cj.prototype.T=function(){window.document.title=window.chrome.i18n.getMessage("CHROME_HANGOUTS_SHORT_NAME");this.c=window.chrome.runtime.connect({name:this.f});var a=this;this.c.onMessage.addListener(function(b){switch(_.Pc(new _.J,b).c){case "focus":Dj(a);a.sendMessage("extensionLibrary",["selectTab",a.f,!0,!0]);window.focus();break;case "close":a.h()}});this.a.set("StartOnBrowserLaunch",["BrowserStartup",1]);this.a.set("StopOnBrowserClose",["Shutdown",1]);this.a.set("TopMost",["TopMost",1]);this.a.set("TrayIcon",
["TrayIcon",1]);_.gd(_.Q("fieldsetDestPage"));Ej("legendApp",window.chrome.i18n.getMessage("QUASAR_LEGEND_STARTUP_SHUTDOWN"));Ej("legendNotice",window.chrome.i18n.getMessage("QUASAR_LEGEND_NOTIFICATIONS"));Fj(this,"StartOnBrowserLaunch",window.chrome.i18n.getMessage("CHROME_EXT_RUN_AT_BROWSER_START"));Fj(this,"StopOnBrowserClose",window.chrome.i18n.getMessage("CHROME_EXT_RUN_AFTER_BROWSER_CLOSE"));Fj(this,"TrayIcon",window.chrome.i18n.getMessage("QUASAR_LABEL_TRAY_ICON"));_.Wc?Fj(this,"TopMost",window.chrome.i18n.getMessage("CHROME_EXT_NEW_WINDOWS_TOPMOST")):
Gj(this,"TopMost");_.Oc()&&Gj(this,"TrayIcon");Dj(this);var b=_.Q("feedbackLink");b.innerText=window.chrome.i18n.getMessage("CHROME_EXT_MENUTEXT_FEEDBACK");b.href=_.ce();b=_.Q("helpLink");b.innerText=window.chrome.i18n.getMessage("QUASAR_HELP");b.href=Bj("https://support.google.com/hangouts?p=help&hl=%s",window.chrome.i18n.getMessage("@@ui_locale"));this.l=_.Q("buttonSave");this.l.innerText=window.chrome.i18n.getMessage("QUASAR_BUTTON_SAVE");this.b.listen(this.l,"click",(0,_.r)(this.w,this),!1);this.j=
_.Q("buttonCancel");this.j.innerText=window.chrome.i18n.getMessage("QUASAR_BUTTON_CANCEL");this.b.listen(this.j,"click",(0,_.r)(this.h,this),!1)};Cj.prototype.init=Cj.prototype.T;
var Hj=function(a,b,c){var d=[];b+=a.a.get(c)[0];a=a.a.get(c)[1];if(1<a)for(c=0;c<a;c++)d.push(_.Q(b+c));else d.push(_.Q(b));return d},Dj=function(a){for(var b=new _.Vc(a.g.get("settings")),c=a.a.M(),d=0;d<c.length;d++){var e=b.getItem(c[d]);if(e){var f=Hj(a,"field",c[d]);if(e.za){var g=e.F();0<=g&&f[g]&&(f[g].checked=!0)}else f[0]&&("boolean"==e.a?e.ya?f[0].checked=!e.F():f[0].checked=e.F():f[0].value=e.F());if(!e.W)for(e=Hj(a,"label",c[d]),g=0;g<e.length;g++)e[g]&&(e[g].disabled=!0),f[g]&&(f[g].disabled=
!0)}}},Ej=function(a,b){var c=_.Q(a);c&&(c.innerText=b)},Fj=function(a,b,c){var d=a.a.get(b)[0];a=a.a.get(b)[1];if(1<a)for(b=0;b<a;b++){var e=_.Q("label"+d+b);e&&c&&(e.innerText=c[b])}else(e=_.Q("label"+d))&&c&&(e.innerText=c)},Gj=function(a,b){var c=a.a.get(b)[0],d=_.Q("field"+c);(d=(c=(c=_.Q("label"+c)||d)&&c.parentNode)&&c.parentNode)&&d.removeChild(c)};
Cj.prototype.w=function(){for(var a=new _.Vc(this.g.get("settings")),b=this.a.M(),c=0;c<b.length;c++){var d=a.getItem(b[c]);if(d){var e=Hj(this,"field",b[c]),f=d.F();if(d.za){for(var g=-1,k=0;k<e.length;k++)if(e[k]&&e[k].checked){g=k;break}-1==g&&(g=0);d.ja=g}else e[0]&&(d.ja="boolean"==d.a?d.ya?!e[0].checked:e[0].checked:e[0].value);f!=d.F()&&(d.ua=!0,a.setItem(d))}}this.g.set("settings",_.Sg(a));this.h()};
Cj.prototype.h=function(){this.sendMessage("settingsManager",["updateSettingsFromStorage"]);window.close()};Cj.prototype.sendMessage=function(a,b,c){c=c?c:""+(0,_.m)();var d=new _.J;_.Qc(d,this.f,"p");null!=a&&(d.h=a);_.Rc(d,c);_.Sc(d,b);this.c&&this.c.postMessage(d.message())};
window.addEventListener("load",function(){_.Yc.ca().T(function(){var a=new _.md;a.a(_.ah,_.Yc.ca());(new Cj(a)).T()})},!1);
}catch(e){_._DumpException(e)}
}).call(this,this.default_settings);
// Google Inc.
